---
sidebar: sidebar 
permalink: scpivs44_create_backup_policies_for_vms_and_datastores.html 
keywords:  
summary: Sie müssen Backup-Richtlinien erstellen, bevor Sie das SnapCenter Plug-in für VMware vSphere zum Backup von VMs und Datastores verwenden. 
---
= Erstellen von Backup-Richtlinien für VMs und Datastores
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie müssen Backup-Richtlinien erstellen, bevor Sie das SnapCenter Plug-in für VMware vSphere zum Backup von VMs und Datastores verwenden.

.Bevor Sie beginnen
* Sie müssen die Voraussetzungen gelesen haben.
* Sie müssen sekundäre Storage-Beziehungen konfiguriert haben.
+
** Wenn Sie Snapshots auf einen sekundären Spiegel- oder Vault-Speicher replizieren, müssen die Beziehungen konfiguriert werden. Der SnapCenter-Administrator muss Ihnen die Storage-VMs sowohl für die Quell- als auch für die Ziel-Volumes zugewiesen haben.
** Um Snapshots für Versionen-FlexibleMirror-Beziehungen auf einem NFS- oder VMFS-Datastore erfolgreich in den sekundären Speicher zu übertragen, stellen Sie sicher, dass der Richtlinientyp SnapMirror „asynchrone Spiegelung“ ist und dass die Option „all_source_Snapshots“ aktiviert ist.
** Wenn die Anzahl der Snapshots auf dem sekundären Speicher (Mirror-Vault) das maximale Limit erreicht, schlägt die Aktivität zur Registrierung von Backups und Anwendung der Aufbewahrung im Backup-Vorgang mit folgender Fehlermeldung fehl: `This snapshot is currently used as a reference snapshot by one or more SnapMirror relationships. Deleting the snapshot can cause future SnapMirror operations to fail.`
+
Um dieses Problem zu beheben, konfigurieren Sie die SnapMirror-Aufbewahrungsrichtlinie für sekundären Speicher, um zu vermeiden, dass die maximale Snapshot-Grenze erreicht wird.

+
Informationen darüber, wie Administratoren Benutzern Ressourcen zuweisen, finden Sie unter https://docs.netapp.com/us-en/snapcenter/concept/concept_types_of_role_based_access_control_in_snapcenter.html["SnapCenter-Informationen zur Nutzung der rollenbasierten Zugriffssteuerung"^].



* Wenn Sie VM-konsistente Backups wünschen, müssen VMware Tools installiert und ausgeführt werden. Um VMs stillzulegen, sind VMware Tools erforderlich. VM-konsistente Backups werden für vVol VMs nicht unterstützt.
* SnapMirror Active Sync ermöglicht Business Services auch bei einem vollständigen Standortausfall den Betrieb weiter und unterstützt Applikationen bei einem transparenten Failover mithilfe einer sekundären Kopie.
+

NOTE: SnapMirror Active Sync wird nur für VMFS Datastores unterstützt.

+
Zum Schutz eines VMFS-Datenspeichers in einer Implementierung mit aktiver SnapMirror Synchronisierung müssen Sie als SnapCenter-Administrator Folgendes tun:

+
** Konfigurieren Sie Cluster und Mediator wie im technischen Bericht beschrieben: https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/mediator-install-task.html["Konfigurieren Sie den ONTAP Mediator und die Cluster für SnapMirror Active Sync"].
** Fügen Sie das dem VMFS-Datastore zugeordnete Volume zur Konsistenzgruppe hinzu und erstellen Sie mithilfe der _AutomatedFailOver_- oder _AutomatedFailOverDuplex_-Schutzrichtlinie zwischen zwei ONTAP-Speichersystemen eine Datensicherungsbeziehung. _AutomaticatedFailOverDuplex_-Richtlinie wird ab ONTAP 9.15.1 unterstützt.





NOTE: In der Fan-out-Konfiguration wird die Konsistenzgruppe für einen tertiären Standort nicht unterstützt.

.Über diese Aufgabe
Die meisten Felder auf diesen Assistentenseiten sind selbsterklärend. In den folgenden Informationen werden einige der Felder beschrieben, für die Sie möglicherweise eine Anleitung benötigen.

.Schritte
. Wählen Sie im linken Navigationsbereich des SCV-Plug-ins *Richtlinien* aus.
. Wählen Sie auf der Seite *Policies* *Create* aus, um den Assistenten zu starten.
. Geben Sie auf der Seite *New Backup Policy* den Richtliniennamen und eine Beschreibung ein.
+
** Verknüpfter Modus
+
Im Linked-Modus besitzt jedes vCenter eine separate virtuelle Appliance. Daher können Sie doppelte Namen in allen vCenters verwenden. Sie müssen die Richtlinie jedoch im selben vCenter wie die Ressourcengruppe erstellen.

** Nicht unterstützte Zeichen
+
Verwenden Sie nicht die folgenden Sonderzeichen in VMs, Datenspeicher, Cluster, Richtlinien, Backups, Oder Ressourcengruppennamen: % & * € # @ ! \ / : * ? " < > - | ; ' und Leerzeichen.

+
Ein Unterstrich (_) ist zulässig.



. Geben Sie die Frequenzeinstellungen an.
+
Die Richtlinie gibt nur die Backup-Häufigkeit an. Der spezifische Schutzzeitplan für das Sichern ist in der Ressourcengruppe festgelegt. Daher können zwei oder mehr Ressourcengruppen dieselbe Richtlinien- und Backup-Häufigkeit teilen, jedoch unterschiedliche Backup-Pläne haben.

. Aktivieren Sie das Kontrollkästchen *Sperrfrist*, um die Snapshot-Sperrung zu aktivieren. Sie können die Sperrzeiten für primäre und sekundäre Snapshots als Tage/Monate/Jahre auswählen.
+

NOTE: Unabhängig vom in der ONTAP SnapMirror-Richtlinie festgelegten Aufbewahrungswert wird die sekundäre Snapshot-Kopie vor der angegebenen sekundären Snapshot-Sperrfrist nicht gelöscht.

. Legen Sie die Aufbewahrungseinstellungen fest.
+

IMPORTANT: Sie sollten den Aufbewahrungswert auf 2 Backups oder höher einstellen, wenn Sie die SnapVault-Replikation aktivieren möchten. Wenn Sie die Aufbewahrungsanzahl auf 1 Backup gesetzt haben, kann der Aufbewahrungsvorgang fehlschlagen. Das liegt daran, dass der erste Snapshot der Referenz-Snapshot für die SnapVault-Beziehung ist, bis der neuere Snapshot auf das Ziel repliziert wird.

+

NOTE: Der maximale Aufbewahrungswert beträgt 1018 Backups. Backups schlagen fehl, wenn die Aufbewahrung auf einen Wert festgelegt ist, der höher ist, als die zugrunde liegende ONTAP Version unterstützt. Das gilt auch für das Spanning von Datenspeichern.



. Geben Sie in den Feldern *Replikation* den Replikationstyp auf sekundären Speicher an, wie in der folgenden Tabelle dargestellt:
+
|===
| Für dieses Feld… | Do this… 


| Aktualisierung von SnapMirror nach dem Backup  a| 
Wählen Sie diese Option aus, um Spiegelkopien von Backup-Sets auf einem anderen Volume zu erstellen, das über eine SnapMirror Beziehung zum primären Backup Volume verfügt. Wenn ein Volume mit einer Mirror-Vault-Beziehung konfiguriert ist, müssen Sie nur die Option *Update SnapVault after Backup* auswählen, wenn Sie Backups auf die Mirror-Vault Ziele kopieren möchten.


NOTE: Diese Option wird für Datastores in FlexGroup Volumes im SnapCenter Plug-in für VMware vSphere 4.5 und höher unterstützt.


NOTE: Zum Schutz des VMFS-Datastore auf der Bereitstellung von SnapMirror Active Sync müssen Sie die im Abschnitt _before you begin_ genannten Voraussetzungen erfüllen und *Update SnapMirror after Backup* aktivieren.



| SnapVault nach Backup aktualisieren  a| 
Wählen Sie diese Option aus, um Disk-to-Disk Backup-Replikation auf einem anderen Volume mit einer SnapVault-Beziehung zum primären Backup Volume durchzuführen.


IMPORTANT: Wenn ein Volume mit einer Mirror-Vault-Beziehung konfiguriert ist, müssen Sie nur diese Option auswählen, wenn Sie Backups auf die Mirror-Vault Ziele kopieren möchten.


NOTE: Diese Option wird für Datastores in FlexGroup Volumes im SnapCenter Plug-in für VMware vSphere 4.5 und höher unterstützt.



| Snapshot-Etikett  a| 
Geben Sie ein optionales, benutzerdefiniertes Etikett ein, das zu SnapVault- und SnapMirror-Snapshots, die mit dieser Richtlinie erstellt wurden, hinzugefügt werden soll. Das Snapshot-Label hilft, mit dieser Richtlinie erstellte Snapshots von anderen Snapshots auf dem sekundären Storage-System zu unterscheiden.


NOTE: Für Snapshot-Beschriftungen sind maximal 31 Zeichen zulässig.

|===
. Optional: Wählen Sie in den Feldern *Erweitert* die gewünschten Felder aus. In der folgenden Tabelle sind die Details zum Advanced Field Portal aufgeführt.
+
|===
| Für dieses Feld… | Do this… 


| VM-Konsistenz  a| 
Aktivieren Sie dieses Kontrollkästchen, um die VMs stillzulegen und jedes Mal, wenn der Backup-Job ausgeführt wird, einen VMware-Snapshot zu erstellen.

Diese Option wird für VVols nicht unterstützt. Bei vVol VMs werden nur absturzkonsistente Backups durchgeführt.


IMPORTANT: Sie müssen VMware Tools auf der VM ausführen, um VM-konsistente Backups durchzuführen. Wenn VMware-Tools nicht ausgeführt werden, wird stattdessen ein Crash-konsistentes Backup durchgeführt.


NOTE: Wenn Sie das Kontrollkästchen für die Konsistenz der VM aktivieren, können Backup-Vorgänge länger dauern und mehr Speicherplatz benötigen. In diesem Szenario werden die VMs zuerst stillgelegt, dann führt VMware einen VM-konsistenten Snapshot durch, dann führt SnapCenter seinen Backup-Vorgang durch und anschließend werden die VM-Vorgänge wieder aufgenommen. Der VM-Gastspeicher ist nicht in VM Consistency Snapshots enthalten.



| Einbeziehen von Datastores mit unabhängigen Festplatten | Aktivieren Sie dieses Kontrollkästchen, um alle Datenspeicher mit unabhängigen Festplatten, die temporäre Daten enthalten, in das Backup einzubeziehen. 


| Skripte  a| 
Geben Sie den vollständig qualifizierten Pfad des Prescript oder Postscripts ein, das das SnapCenter-Plug-in für VMware vSphere vor oder nach Sicherungsvorgängen ausführen soll. Sie können beispielsweise ein Skript ausführen, um SNMP-Traps zu aktualisieren, Warnmeldungen zu automatisieren und Protokolle zu senden. Der Skriptpfad wird zum Zeitpunkt der Ausführung des Skripts validiert.


NOTE: Prescripts und Postscripts müssen auf der VM der virtuellen Appliance liegen. Um mehrere Skripte einzugeben, drücken Sie nach jedem Skriptpfad *Enter*, um jedes Skript in einer eigenen Zeile aufzulisten. Das Zeichen „;“ ist nicht zulässig.

|===
. Wählen Sie *Hinzufügen*
+
Sie können die Erstellung der Richtlinie überprüfen und die Richtlinienkonfiguration überprüfen, indem Sie die Richtlinie auf der Seite Richtlinien auswählen.


