---
sidebar: sidebar 
permalink: scpivs44_rest_api_workflows__modify_built-in_schedules.html 
keywords:  
summary: Um integrierte Zeitpläne für VMware vSphere Web-Client-Jobs mit dem SnapCenter Plug-in für VMware vSphere REST-APIs zu ändern, müssen Sie die vorgegebene Sequenz von REST-API-Aufrufen befolgen. 
---
= REST-API-Workflow zum Ändern integrierter Zeitpläne
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Um integrierte Zeitpläne für VMware vSphere Web-Client-Jobs mit dem SnapCenter Plug-in für VMware vSphere REST-APIs zu ändern, müssen Sie die vorgegebene Sequenz von REST-API-Aufrufen befolgen.

Integrierte Zeitpläne sind die Zeitpläne, die als Teil des Produkts bereitgestellt werden, z. B. der Zeitplan für den MySQL-Datenbank-Dump. Sie können die folgenden Zeitpläne ändern:
`Schedule-DatabaseDump`
`Schedule-PurgeBackups`
`Schedule-AsupDataCollection`
`Schedule-ComputeStorageSaving`
`Schedule-PurgeJobs`

Fügen Sie für jede REST-API hinzu `https://<server>:<port>` An der Vorderseite der REST-API zu einem vollständigen Endpunkt

|===
| Schritt | REST API | Kommentare 


| 1 | `/4.1/schedules` | `Get all built-in` Zeitpläne erhalten eine Liste der Jobpläne, die ursprünglich im Produkt bereitgestellt wurden. Notieren Sie sich den Planungsnamen, den Sie ändern möchten, und den zugeordneten cron-Ausdruck. 


| 2 | `/4.1/schedules` | `Modify any built-in schedule` Ändert den benannten Zeitplan. Übergeben Sie den Planungsnamen aus Schritt 1 und erstellen Sie einen neuen cron-Ausdruck für den Zeitplan. 
|===