---
sidebar: sidebar 
permalink: scpivs44_log_in_to_the_snapcenter_vmware_vsphere_web_client.html 
keywords:  
summary: Wenn das SnapCenter Plug-in für VMware vSphere implementiert wird, wird ein VMware vSphere Client in vCenter installiert, der auf dem vCenter Bildschirm mit anderen vSphere Clients angezeigt wird. 
---
= Melden Sie sich beim SnapCenter VMware vSphere-Client an
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn das SnapCenter Plug-in für VMware vSphere implementiert wird, wird ein VMware vSphere Client in vCenter installiert, der auf dem vCenter Bildschirm mit anderen vSphere Clients angezeigt wird.

.Bevor Sie beginnen
Transport Layer Security (TLS) muss in vCenter aktiviert sein. Lesen Sie die VMware-Dokumentation.

.Schritte
. Navigieren Sie in Ihrem Browser zu VMware vSphere vCenter.
. Melden Sie sich auf der Seite *VMware vCenter Single Sign-On* an.
+

IMPORTANT: Klicken Sie auf die Schaltfläche *Login*. Aufgrund eines bekannten VMware-Problems, verwenden Sie nicht den EINGABETASTE, um sich anzumelden. Weitere Informationen finden Sie in der VMware-Dokumentation zu Problemen mit dem ESXi Embedded Host Client.

. Klicken Sie auf der Seite *VMware vSphere Client* in der Symbolleiste auf Menü und wählen Sie dann *SnapCenter Plug-in für VMware vSphere*.

