---
sidebar: sidebar 
permalink: scpivs44_overview_of_different_snapcenter_guis.html 
keywords:  
summary: Das SnapCenter Plug-in für VMware vSphere ist ein Standalone-Plug-in, das sich von anderen SnapCenter-Plug-ins unterscheidet. Sie müssen die VMware vSphere Client GUI in vCenter für alle Backup- und Restore-Vorgänge für VMs, VMDKs und Datastores nutzen. 
---
= Überblick über die verschiedenen SnapCenter GUIs
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
In Ihrer SnapCenter-Umgebung müssen die Datensicherung und das Management über die entsprechende GUI durchgeführt werden.

Das SnapCenter Plug-in für VMware vSphere ist ein Standalone-Plug-in, das sich von anderen SnapCenter-Plug-ins unterscheidet. Sie müssen die VMware vSphere Client GUI in vCenter für alle Backup- und Restore-Vorgänge für VMs, VMDKs und Datastores nutzen. Darüber hinaus verwenden Sie das Web-Client-GUI-Dashboard, um die Liste der geschützten und nicht geschützten VMs zu überwachen. Für alle anderen SnapCenter Plug-in-Vorgänge (applikationsbasierte Plug-ins) wie Backup und Restore sowie Job-Monitoring verwenden Sie die GUI von SnapCenter.

Zur Sicherung von VMs und Datastores nutzen Sie die Schnittstelle des VMware vSphere Clients. Die Web-Client-GUI ist in die NetApp Snapshot Technologie auf dem Storage-System integriert. So können Sie VMs und Datenspeicher in Sekundenschnelle sichern und VMs wiederherstellen, ohne einen ESXi Host offline zu schalten.

Es gibt auch eine Management-GUI zum Durchführen administrativer Vorgänge im SnapCenter VMware Plug-in.

Die folgende Tabelle zeigt die von der SnapCenter GUI durchführen Vorgänge.

|===
| Verwenden Sie diese GUI… | Zur Ausführung dieser Vorgänge... | Und für den Zugriff auf diese Backups... 


| SnapCenter vSphere Client-GUI | VM- und Datastore-Backup VMDK-Anbindung und -Trennung Datastore-Mount und unmounten Sie VM und VMDK Restore der Gastdatei und Ordner | Backups von VMs und Datastores mithilfe der VMware vSphere Client-GUI. 


| SnapCenter GUI | Backup und Restore von Datenbanken und Applikationen auf VMs, einschließlich der Sicherung von Datenbanken für Microsoft SQL Server, Microsoft Exchange und Oracle. Datenbankklone | Backups werden über die GUI von SnapCenter durchgeführt. 


| SnapCenter Plug-in für Management-GUI von VMware vSphere | Ändern der Netzwerkkonfiguration Erstellen Sie ein Supportpaket Ändern der NTP-Servereinstellungen Deaktivieren/Aktivieren des Plug-ins | N.A. 


| VCenter GUI | Hinzufügen von SCV-Rollen zu vCenter Active Directory-Benutzern Hinzufügen von Ressourcenzugriff für Benutzer oder Gruppen | N.A. 
|===
Für VM-konsistente Backup- und Restore-Vorgänge müssen Sie die VMware vSphere Client GUI verwenden. Obwohl einige Vorgänge mithilfe von VMware Tools beispielsweise beim Mounten oder Umbenennen eines Datastores möglich sind, werden diese Vorgänge nicht im SnapCenter Repository registriert und werden nicht erkannt.

SnapCenter unterstützt keine einzelnen Snapshots von Datenbanken und VMs zusammen. Backups für VMs und Datenbanken müssen unabhängig geplant und ausgeführt werden. Dadurch werden separate Snapshots erstellt, selbst wenn die Datenbanken und VMs im gleichen Volume gehostet werden. Applikationskonsistente Backups müssen über die SnapCenter GUI geplant werden. VM-konsistente Backups müssen über die VMware vSphere Client GUI geplant werden.
