---
sidebar: sidebar 
permalink: scpivs44_manage_policies.html 
keywords:  
summary: Backup-Richtlinien für das SnapCenter Plug-in für VMware vSphere lassen sich erstellen, ändern, anzeigen, trennen und löschen. Zur Durchführung von Datensicherungsvorgängen sind Richtlinien erforderlich. 
---
= Management von Richtlinien
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Backup-Richtlinien für das SnapCenter Plug-in für VMware vSphere lassen sich erstellen, ändern, anzeigen, trennen und löschen. Zur Durchführung von Datensicherungsvorgängen sind Richtlinien erforderlich.



== Richtlinien trennen

Sie können Richtlinien aus einer SnapCenter VMware Plug-in-Ressourcengruppe trennen, wenn diese Richtlinien nicht mehr für die Datensicherung der Ressourcen sorgen sollen. Sie müssen eine Richtlinie trennen, bevor Sie sie entfernen können oder bevor Sie die Zeitplanfrequenz ändern.

.Über diese Aufgabe
Die Richtlinien zum Trennen von Richtlinien von SnapCenter VMware Plug-in-Ressourcengruppen unterscheiden sich von den Richtlinien für SnapCenter-Ressourcengruppen. Bei einer VMware vSphere Web-Client-Ressourcengruppe können alle Richtlinien abgetrennt werden, wodurch die Ressourcengruppe ohne Richtlinie bleibt. Um jedoch Datensicherungsvorgänge an dieser Ressourcengruppe durchzuführen, müssen Sie mindestens eine Richtlinie anhängen.

.Schritte
. Klicken Sie im linken Navigator-Bereich des VMware vSphere Web-Clients auf *Resource Groups*, wählen Sie dann eine Ressourcengruppe aus und klicken Sie auf *Bearbeiten*.
. Deaktivieren Sie auf der Seite *Richtlinien* des Assistenten * Ressourcengruppe bearbeiten* das Häkchen neben den Richtlinien, die Sie entfernen möchten.
+
Sie können der Ressourcengruppe auch eine Richtlinie hinzufügen, indem Sie die Richtlinie prüfen.

. Nehmen Sie zusätzliche Änderungen an der Ressourcengruppe im Rest des Assistenten vor, und klicken Sie dann auf *Fertig stellen*.




== Richtlinien ändern

Sie können Richtlinien für ein SnapCenter Plug-in für eine VMware vSphere Ressourcengruppe ändern. Sie können die Häufigkeit, die Replizierungsoptionen, die Aufbewahrungseinstellungen für Snapshot Kopien oder die Informationen zu Skripten ändern, während eine Richtlinie einer Ressourcengruppe zugeordnet ist.

.Über diese Aufgabe
Das Ändern der Backup-Richtlinien für das SnapCenter VMware Plug-in unterscheidet sich von der Änderung der Backup-Richtlinien für applikationsbasierte SnapCenter Plug-ins. Wenn Sie die Plug-in-Richtlinien ändern, müssen Sie keine Richtlinien von Ressourcengruppen trennen.

Bevor Sie die Replizierungs- oder Aufbewahrungseinstellungen ändern, sollten Sie die möglichen Folgen berücksichtigen.

* Erhöhen der Replizierungs- oder Aufbewahrungseinstellungen
+
Backups sammeln sich weiter an, bis sie die neue Einstellung erreichen.

* Verringerung der Replizierungs- oder Aufbewahrungseinstellungen
+
Backups, die über die neue Einstellung hinausgehen, werden bei der Durchführung des nächsten Backups gelöscht.




NOTE: Zum Ändern eines Zeitplans für eine SnapCenter VMware Plug-in-Richtlinie müssen Sie den Zeitplan in der Plug-in-Ressourcengruppe ändern.

.Schritte
. Klicken Sie im linken Navigator-Bereich des VMware vSphere Web-Clients auf *Richtlinien*, wählen Sie dann eine Richtlinie aus und klicken Sie auf *Bearbeiten*.
. Ändern Sie die Richtlinienfelder.
. Wenn Sie fertig sind, klicken Sie auf *Aktualisieren*.


Die Änderungen werden wirksam, wenn das nächste geplante Backup durchgeführt wird.



== Richtlinien löschen

Wenn Sie keine konfigurierte Backup-Richtlinie mehr für das SnapCenter Plug-in für VMware vSphere benötigen, möchten Sie sie möglicherweise löschen.

.Bevor Sie beginnen
Sie müssen die Richtlinie von allen Ressourcengruppen in der virtuellen Appliance für SnapCenter getrennt haben, bevor Sie sie löschen können.

.Schritte
. Klicken Sie im linken Navigator-Bereich des VMware vSphere Web-Clients auf *Richtlinien*, wählen Sie dann eine Richtlinie aus und klicken Sie auf *Entfernen*.
. Klicken Sie im Bestätigungsdialogfeld auf *OK*.

