---
sidebar: sidebar 
permalink: scpivs44_set_up_proxy_vms_for_restore_operations.html 
keywords:  
summary: Wenn Sie eine Proxy-VM zum Anschließen einer virtuellen Festplatte für die Wiederherstellung von Gastdateien verwenden möchten, müssen Sie die Proxy-VM einrichten, bevor Sie mit der Wiederherstellung beginnen. Sie können zwar jederzeit eine Proxy-VM einrichten, jedoch ist es unter Umständen günstiger, sie sofort nach Abschluss der Plug-in-Bereitstellung einzurichten. 
---
= Einrichten von Proxy-VMs für Wiederherstellungsvorgänge
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie eine Proxy-VM zum Anschließen einer virtuellen Festplatte für die Wiederherstellung von Gastdateien verwenden möchten, müssen Sie die Proxy-VM einrichten, bevor Sie mit der Wiederherstellung beginnen. Sie können zwar jederzeit eine Proxy-VM einrichten, jedoch ist es unter Umständen günstiger, sie sofort nach Abschluss der Plug-in-Bereitstellung einzurichten.

.Schritte
. Wählen Sie im Fenster vSphere Client Shortcuts unter Plug-ins *SnapCenter Plug-in für VMware vSphere* aus.
. Wählen Sie in der linken Navigation *Guest File Restore*.
. Führen Sie im Abschnitt * Ausführen als Anmeldeinformationen* einen der folgenden Schritte aus:
+
|===
| Um dies zu tun… | Do this… 


| Verwenden Sie vorhandene Anmeldedaten | Wählen Sie eine der konfigurierten Anmeldeinformationen aus. 


| Neue Anmeldedaten hinzufügen  a| 
.. Wählen Sie *Hinzufügen*.
.. Geben Sie im Dialogfeld *Ausführen als Anmeldeinformationen* die Anmeldeinformationen ein.
.. Wählen Sie *Select VM* aus, und wählen Sie dann im Dialogfeld *Proxy VM* eine VM aus. Wählen Sie *Speichern*, um zum Dialogfeld *Run As Credentials* zurückzukehren.
.. Geben Sie die Anmeldeinformationen ein. Für den Benutzernamen müssen Sie „Administrator“ eingeben.


|===
+
Das SnapCenter Plug-in für VMware vSphere verwendet die ausgewählten Anmeldeinformationen, um sich bei der ausgewählten Proxy-VM anzumelden.

+
Die Anmeldeinformationen „Ausführen als“ müssen der standardmäßige Domänenadministrator sein, der von Windows oder dem integrierten lokalen Administrator bereitgestellt wird. Workgroup-Benutzer können das integrierte lokale Administratorkonto verwenden.

. Wählen Sie im Abschnitt *Proxy Credentials* *Hinzufügen* aus, um eine VM hinzuzufügen, die als Proxy verwendet werden soll.
. Füllen Sie im Dialogfeld *Proxy VM* die Informationen aus, und wählen Sie dann *Speichern*.



NOTE: Sie müssen die Proxy-VM aus dem SnapCenter-Plug-in für VMware vSphere-UI löschen, bevor Sie sie vom ESXi-Host löschen können.
