---
sidebar: sidebar 
permalink: scpivs44_unmount_a_backup.html 
keywords:  
summary: Sie können die Bereitstellung eines Backups aufheben, wenn Sie nicht mehr auf die Dateien im Datastore zugreifen müssen. 
---
= Heben Sie die Bereitstellung eines Backups auf
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können die Bereitstellung eines Backups aufheben, wenn Sie nicht mehr auf die Dateien im Datastore zugreifen müssen.

Wenn ein Backup in der Benutzeroberfläche des VMware vSphere-Clients als gemountet aufgeführt ist, es aber nicht im Bildschirm zum Unmounten von Backups aufgeführt ist, müssen Sie die REST-API verwenden. `/backup/{backup-Id}/cleanup` um die Out-of-Bound-Datenspeicher zu bereinigen und dann den Unmount-Vorgang erneut zu versuchen.

Wenn Sie versuchen, eine Sicherungskopie eines NFS-Datenspeichers auf einer Speicher-VM (SVM) mit dem Stammvolume in einer Lastenteilungs-Spiegelbeziehung zu mounten, tritt möglicherweise der Fehler `You might have reached the maximum number of NFS volumes configured in the vCenter. Check the vSphere Client for any error messages.` Um dieses Problem zu vermeiden, ändern Sie die Einstellung für die maximalen Volumes, indem Sie zu *ESX* > *Verwalten* > *Einstellungen* > *Erweiterte Systemeinstellungen* navigieren und den Wert NFS.MaxVolumes ändern.  Der Maximalwert ist 256.

.Schritte
. Wählen Sie auf der Seite VMware vSphere Client Shortcuts *Storage* aus.
. Klicken Sie im linken Navigationsbereich mit der rechten Maustaste auf einen Datastore, wählen Sie dann *SnapCenter Plug-in für VMware vSphere* in der Dropdown-Liste aus, und wählen Sie dann *Unmount* in der sekundären Dropdown-Liste aus.
+

IMPORTANT: Stellen Sie sicher, dass Sie den richtigen Datastore zum Aufheben der Bereitstellung auswählen. Andernfalls können Sie Auswirkungen auf die Produktionsarbeit haben.

. Wählen Sie im Dialogfeld *Unmounten geklonter Datastore* einen Datastore aus, aktivieren Sie das Kontrollkästchen *Unmounten des geklonten Datastore* und wählen Sie dann *Unmounten* aus.

