---
sidebar: sidebar 
permalink: scpivs44_predefined_roles_packaged_with_snapcenter.html 
keywords:  
summary: Das SnapCenter Plug-in für VMware vSphere bietet eine Reihe vordefinierter Rollen, mit denen Benutzer SnapCenter-Aufgaben ausführen können, um die Arbeit mit RBAC für vCenter Server zu vereinfachen. Es gibt auch eine schreibgeschützte Rolle, mit der Benutzer SnapCenter-Informationen anzeigen, aber keine Aufgaben ausführen können. 
---
= Vordefinierte Rollen in Paketen mit SnapCenter Plug-in für VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Das SnapCenter Plug-in für VMware vSphere bietet eine Reihe vordefinierter Rollen, mit denen Benutzer SnapCenter-Aufgaben ausführen können, um die Arbeit mit RBAC für vCenter Server zu vereinfachen. Es gibt auch eine schreibgeschützte Rolle, mit der Benutzer SnapCenter-Informationen anzeigen, aber keine Aufgaben ausführen können.

Die vordefinierten Rollen verfügen sowohl über die erforderlichen SnapCenter-spezifischen Berechtigungen als auch über die nativen vCenter Server-Berechtigungen, um sicherzustellen, dass Aufgaben korrekt ausgeführt werden. Darüber hinaus sind die Rollen so eingerichtet, dass sie über die erforderlichen Berechtigungen für alle unterstützten Versionen von vCenter Server verfügen.

Als Administrator können Sie diese Rollen den entsprechenden Benutzern zuweisen.

Das SnapCenter-Plug-in für VMware vSphere setzt diese Rollen bei jedem Neustart des vCenter-Webclient-Dienstes oder bei der Änderung der Installation auf die Standardwerte (anfängliche Berechtigungseinstellung) zurück. Wenn Sie das SnapCenter-Plug-in für VMware vSphere aktualisieren, werden die vordefinierten Rollen automatisch aktualisiert, um mit dieser Version des Plug-ins zu arbeiten.

Sie können die vordefinierten Rollen in der vCenter-GUI sehen, indem Sie wie in der folgenden Tabelle dargestellt auf *Menü > Administration > Rollen* klicken.

|===
| Rolle | Beschreibung 


| SCV-Administrator | Bietet alle nativen vCenter Server und SnapCenter-spezifischen Berechtigungen, die zur Ausführung aller SnapCenter Plug-ins für VMware vSphere Aufgaben erforderlich sind Ab Version SCV 6.1 wird dieser Rolle eine neue Berechtigung zum Erstellen eines sekundären Schutzes hinzugefügt. 


| SCV-Backup | Bereitstellung aller nativen vCenter Server und SnapCenter-spezifischen Berechtigungen, die für das Backup von vSphere Objekten (Virtual Machines und Datastores) erforderlich sind Der Benutzer hat auch Zugriff auf die Konfigurationsberechtigung. Der Benutzer kann Backups nicht wiederherstellen. Ab Version SCV 6.1 wird dieser Rolle eine neue Berechtigung zum Erstellen eines sekundären Schutzes hinzugefügt. 


| Wiederherstellung der SCV-Gastdatei | Bietet alle nativen vCenter Server und SnapCenter-spezifischen Berechtigungen, die für die Wiederherstellung von Gastdateien und Ordnern erforderlich sind Der Benutzer kann keine VMs oder VMDKs wiederherstellen. 


| SCV-Wiederherstellung | Bietet alle nativen vCenter Server- und SnapCenter-spezifischen Berechtigungen, die erforderlich sind, um vSphere Objekte wiederherzustellen, die mit dem SnapCenter Plug-in für VMware vSphere gesichert wurden, und um Gastdateien und -Ordner wiederherzustellen. Der Benutzer hat auch Zugriff auf die Konfigurationsberechtigung. Der Benutzer kann vSphere-Objekte nicht sichern. 


| SCV-Ansicht | Bietet schreibgeschützten Zugriff auf alle SnapCenter Plug-in für VMware vSphere-Backups, Ressourcengruppen und Richtlinien. 
|===