---
sidebar: sidebar 
permalink: scpivs44_ontap_rbac_features_in_snapcenter.html 
keywords:  
summary: 'Das SnapCenter VMware Plug-in nutzt die rollenbasierte Zugriffssteuerung von vCenter Server, die SnapCenter RBAC (bei Bedarf zur Unterstützung applikationsbasierter Vorgänge) und die ONTAP RBAC. So können Sie festlegen, welche SnapCenter Aufgaben ein bestimmter Benutzer auf Objekten in einem bestimmten Storage-System ausführen kann.' 
---
= ONTAP RBAC-Funktionen im SnapCenter Plug-in für VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/



NOTE: ONTAP RBAC ist nur für applikationskonsistente (Applikations-Over VMDK) Jobs des SnapCenter Servers gültig.

[role="lead"]
Mit der rollenbasierten Zugriffssteuerung (Role Based Access Control, RBAC) von ONTAP können Sie den Zugriff auf bestimmte Storage-Systeme steuern und die Aktionen ausführen, die ein Benutzer auf diesen Storage-Systemen durchführen kann. Das SnapCenter VMware Plug-in nutzt die rollenbasierte Zugriffssteuerung von vCenter Server, die SnapCenter RBAC (bei Bedarf zur Unterstützung applikationsbasierter Vorgänge) und die ONTAP RBAC. So können Sie festlegen, welche SnapCenter Aufgaben ein bestimmter Benutzer auf Objekten in einem bestimmten Storage-System ausführen kann.

SnapCenter verwendet die von Ihnen festgelegten Anmeldedaten (Benutzername und Passwort) zur Authentifizierung jedes Storage-Systems und zur Bestimmung, welche Vorgänge auf diesem Storage-System ausgeführt werden können. Das SnapCenter VMware Plug-in verwendet einen Satz an Anmeldedaten für jedes Storage-System. Diese Anmeldedaten bestimmen alle Aufgaben, die auf dem Storage-System ausgeführt werden können. Das heißt, die Anmeldedaten gelten für SnapCenter, nicht für einen einzelnen SnapCenter-Benutzer.

ONTAP RBAC gilt nur für den Zugriff auf Storage-Systeme und zur Durchführung von SnapCenter Aufgaben, beispielsweise für das Backup von VMs. Wenn Sie nicht über die entsprechenden ONTAP RBAC-Berechtigungen für ein bestimmtes Storage-System verfügen, können Sie keine Aufgaben auf einem vSphere Objekt ausführen, das auf diesem Storage-System gehostet wird.

Jedem Speichersystem ist ein Satz von ONTAP-Berechtigungen zugeordnet.

Die Nutzung der ONTAP RBAC und der vCenter Server RBAC bietet folgende Vorteile:

* Sicherheit
+
Der Administrator kann steuern, welche Benutzer Aufgaben sowohl auf feingranularen vCenter Server-Objektebene als auch auf Storage-System-Ebene ausführen können.

* Audit-Informationen
+
In vielen Fällen erstellt SnapCenter ein Audit-Trail im Storage-System, über das Sie Ereignisse zurück an den vCenter Benutzer nachverfolgen können, der die Storage-Änderungen durchgeführt hat.

* Benutzerfreundlichkeit
+
Sie können die Controller-Anmeldedaten an einer Stelle beibehalten.


