---
sidebar: sidebar 
permalink: scpivs44_restart_the_vmware_vsphere_web_client_service.html 
keywords:  
summary: Wenn sich der SnapCenter VMware vSphere Client falsch verhält, müssen Sie möglicherweise den Browser-Cache löschen. Wenn das Problem weiterhin besteht, starten Sie den Web-Client-Service neu. 
---
= Starten Sie den VMware vSphere-Client-Service neu
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn sich der SnapCenter VMware vSphere Client falsch verhält, müssen Sie möglicherweise den Browser-Cache löschen. Wenn das Problem weiterhin besteht, starten Sie den Web-Client-Service neu.



== Starten Sie den VMware vSphere-Client-Service in einem Linux-vCenter

.Bevor Sie beginnen
Sie müssen vCenter 7.0U1 oder höher ausführen.

.Schritte
. Verwenden Sie SSH, um sich bei der vCenter Server Appliance als Root anzumelden.
. Greifen Sie mit dem folgenden Befehl auf die Appliance-Shell oder DIE BASH-Shell zu:
+
`shell`

. Beenden Sie den Web-Client-Service mit dem folgenden HTML5-Befehl:
+
`service-control --stop vsphere-ui`

. Löschen Sie alle veralteten HTML5-Scvm-Pakete auf vCenter mithilfe des folgenden Shell-Befehls:
+
`etc/vmware/vsphere-ui/vc-packages/vsphere-client-serenity/`

+
`rm -rf com.netapp.scv.client-<version_number>`

+

IMPORTANT: Entfernen Sie die Pakete VASA oder vCenter 7.x und höher nicht.

. Starten Sie den Web-Client-Dienst mit dem folgenden HTML5-Befehl:
+
`service-control --start vsphere-ui`


