---
sidebar: sidebar 
permalink: scpivs44_manage_resource_groups.html 
keywords:  
summary: Sie können Backup-Ressourcengruppen erstellen, ändern und löschen und Backup-Vorgänge für Ressourcengruppen durchführen. 
---
= Verwalten von Ressourcengruppen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können Backup-Ressourcengruppen erstellen, ändern und löschen und Backup-Vorgänge für Ressourcengruppen durchführen.


NOTE: Ressourcengruppen werden als Backup-Jobs in der Virtual Storage Console (VSC) bezeichnet.



== Unterbrechen und Fortsetzen des Betriebs von Ressourcengruppen

Unterbrechen Sie geplante Vorgänge für eine Ressourcengruppe.  Aktivieren Sie sie bei Bedarf erneut.

.Schritte
. Wählen Sie im linken Navigationsbereich des SCV-Plug-ins *Ressourcengruppen*, wählen Sie eine Ressourcengruppe aus und wählen Sie *Unterbrechen* (oder wählen Sie *Fortsetzen*) aus.
. Wählen Sie im Bestätigungsfeld zur Bestätigung *OK* aus.


.Nachdem Sie fertig sind
Auf der Seite Ressourcengruppen lautet der Job-Status für die gesperrte Ressource `Under_Maintenance`. Möglicherweise müssen Sie nach rechts in der Tabelle blättern, um die Spalte Job Status anzuzeigen.

Nachdem die Sicherungsvorgänge wieder aufgenommen wurden, ändert sich der Job-Status in `Production`.



== Ressourcengruppen ändern

Ressourcen in Ressourcengruppen in vCenter können entfernt oder hinzugefügt, Richtlinien abgetrennt oder zugewiesen, Zeitpläne geändert oder andere Optionen für Ressourcengruppen geändert werden.

.Über diese Aufgabe
Wenn Sie den Namen einer Ressourcengruppe ändern möchten, verwenden Sie die folgenden Sonderzeichen nicht in VM-, Datastore-, Richtlinien-, Backup- oder Ressourcengruppennamen:

% & * # @ ! \ / : * ? " < > - | ; ' und Leerzeichen. Ein Unterstrich (_) ist zulässig.

.Schritte
. Wählen Sie im linken Navigationsbereich des SCV-Plug-ins *Ressourcengruppen*, wählen Sie dann eine Ressourcengruppe aus und wählen Sie *Bearbeiten* aus.
. Wählen Sie in der linken Liste im Assistenten *Ressourcengruppe bearbeiten* die Kategorie aus, die Sie ändern möchten, und geben Sie Ihre Änderungen ein.
+
Sie können Änderungen in mehreren Kategorien vornehmen. Mit dieser Option können Sie auch sekundäre geschützte Ressourcen bearbeiten.

. Wählen Sie *Weiter*, bis die Übersichtsseite angezeigt wird, und wählen Sie dann *Fertig stellen*.




== Löschen von Ressourcengruppen

Löschen Sie eine Ressourcengruppe in vCenter, wenn Sie die Ressourcen nicht schützen müssen.  Löschen Sie alle Ressourcengruppen, bevor Sie das SnapCenter Plug-in for VMware vSphere entfernen.

.Über diese Aufgabe
Alle Löschvorgänge für Ressourcengruppen werden als erzwungene Löschungen ausgeführt.  Wenn Sie eine Ressourcengruppe löschen, trennt das System alle Richtlinien von der vCenter-Ressourcengruppe, entfernt die Ressourcengruppe aus dem SnapCenter Plug-in for VMware vSphere und löscht alle Sicherungen und Snapshots der Ressourcengruppe.


NOTE: In einer SnapVault -Beziehung können Sie den letzten Snapshot nicht löschen und daher auch nicht die Ressourcengruppe.  Bevor Sie eine Ressourcengruppe in einer SnapVault -Beziehung löschen, entfernen Sie die Beziehung mit System Manager oder ONTAP CLI und löschen Sie dann den letzten Snapshot.

.Schritte
. Wählen Sie im linken Navigationsbereich des SCV-Plug-ins *Ressourcengruppen*, wählen Sie dann eine Ressourcengruppe aus und wählen Sie *Löschen* aus.
. Wählen Sie im Bestätigungsdialogfeld *Ressourcengruppe löschen* zur Bestätigung *OK* aus.  Durch das Löschen einer Ressourcengruppe wird der sekundäre Schutz nicht entfernt.  Verwenden Sie bei Bedarf den System Manager, um den sekundären Schutz zu löschen.  Für die Ressourcengruppe erstellte Konsistenzgruppen werden nicht automatisch entfernt. Sie müssen sie manuell mithilfe von System Manager oder einer anderen unterstützten Schnittstelle aus ONTAP löschen.

