---
sidebar: sidebar 
permalink: scpivs44_how_restore_operations_are_performed.html 
keywords:  
summary: 'Für VMFS Umgebungen verwendet das SnapCenter Plug-in für VMware vSphere Klon- und Mount-Vorgänge mit Storage VMotion, um Restore-Vorgänge durchzuführen. Für NFS-Umgebungen verwendet das Plug-in natives ONTAP Single File SnapRestore (SFSR), um die Effizienz für die meisten Wiederherstellungsvorgänge zu steigern. Das Plug-in für vVol VMs verwendet ONTAP Single File Snapshot Restore und SnapMirror Restore für Restore-Vorgänge.' 
---
= Durchführen von Restore-Vorgängen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Für VMFS Umgebungen verwendet das SnapCenter Plug-in für VMware vSphere Klon- und Mount-Vorgänge mit Storage VMotion, um Restore-Vorgänge durchzuführen. Für NFS-Umgebungen verwendet das Plug-in natives ONTAP Single File SnapRestore (SFSR), um die Effizienz für die meisten Wiederherstellungsvorgänge zu steigern. Für vVol VMs verwendet das Plug-in ONTAP Single File Snapshot Restore (ONTAP SFSR) und SnapMirror Restore für Restore-Vorgänge. Die folgende Tabelle zeigt, wie Wiederherstellungsvorgänge durchgeführt werden.

|===
| Restore-Vorgänge | Von | Durchgeführt mit 


| VMs und VMDKs | Primäre Backups | NFS-Umgebungen: ONTAP Single File SnapRestore VMFS-Umgebungen: Klonen und Mounten mit Storage VMotion 


| VMs und VMDKs | Sekundäre Backups | NFS-Umgebungen: ONTAP Single File SnapRestore VMFS-Umgebungen: Klonen und Mounten mit Storage VMotion 


| Gelöschte VMs und VMDKs | Primäre Backups | NFS-Umgebungen: ONTAP Single File SnapRestore VMFS-Umgebungen: Klonen und Mounten mit Storage VMotion 


| Gelöschte VMs und VMDKs | Sekundäre Backups | NFS-Umgebungen: Klonen und Mounten mit Storage VMotion VMFS-Umgebungen: Klonen und Mounten mit Storage VMotion 


| VMs und VMDKs | VM-konsistente primäre Backups | NFS-Umgebungen: ONTAP Single File SnapRestore VMFS-Umgebungen: Klonen und Mounten mit Storage VMotion 


| VMs und VMDKs | VM-konsistente sekundäre Backups | NFS-Umgebungen: Klonen und Mounten mit Storage VMotion VMFS-Umgebungen: Klonen und Mounten mit Storage VMotion 


| VVol VMs | Absturzkonsistente primäre Backups | Single File SnapRestore von ONTAP für alle Protokolle 


| VVol VMs | Absturzkonsistente sekundäre Backups | ONTAP SnapMirror Restore für alle Protokolle 


| FlexGroup-VMs | Primäre Backups  a| 
NFS-Umgebungen: * ONTAP Single File SnapRestore, wenn Sie ONTAP Version 9.10.1 und höher verwenden * Klonen und Mounten mit Storage VMotion auf früheren Versionen von ONTAP

VMFS-Umgebungen: Nicht unterstützt für FlexGroups



| FlexGroup-VMs | Sekundäre Backups  a| 
NFS-Umgebungen:

* ONTAP SnapMirror Wiederherstellen, wenn Sie ONTAP Version 9.10.1 und höher verwenden
* Klonen und Mounten mit Storage VMotion für ONTAP vorherige Versionen


VMFS-Umgebungen: Nicht unterstützt für FlexGroups

|===

NOTE: Nach dem Ausgleich von vVol Containern können Sie keine vVol VM wiederherstellen.

Die Wiederherstellung von Gastdateien erfolgt sowohl mit Klon- als auch Mount-Vorgängen (nicht Storage VMotion) in NFS- und VMFS-Umgebungen.


IMPORTANT: Während eines Wiederherstellungsvorgangs kann der Fehler auftreten, oder dieser tritt auf `Host unresolved volumes is null` `Exception while calling pre-restore on SCV….Error mounting cloned LUN as datastore…` , wenn das SnapCenter-Plug-in für VMware vSphere versucht, den Klon neu zu signieren. Aufgrund von VMware-Einschränkungen kann das SnapCenter-Plug-in für VMware vSphere den Wert für die automatische Neusignatur in erweiterten ESXi-Hostkonfigurationen nicht steuern. Für NVMe over TCP und NVMe over FC Storage kann SCV keine Controller dynamisch hinzufügen, wenn ein neues Subsystem hinzugefügt wird. Sie sollten die erforderliche Zuordnung vor dem Mount-Vorgang vornehmen.

Weitere Informationen zum Fehler finden Sie unter https://kb.netapp.com/mgmt/SnapCenter/SCV_clone_or_restores_fail_with_error_'Host_Unresolved_volumes_is_null'#["KB-Artikel: SCV-Clone oder Wiederherstellung schlagen mit Fehler 'Host ungelöste Volumes ist Null"^] .
