---
sidebar: sidebar 
permalink: scpivs44_view_status_information.html 
keywords:  
summary: Sie können Statusinformationen im vSphere-Client-Dashboard anzeigen. Die Statusinformationen werden einmal pro Stunde aktualisiert. 
---
= Zeigt Statusinformationen an
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können Statusinformationen im vSphere-Client-Dashboard anzeigen. Die Statusinformationen werden einmal pro Stunde aktualisiert.

.Schritte
. Wählen Sie auf der Verknüpfungsseite des vCenter-Clients die Option SnapCenter-Plug-in für VMware vSphere (SCV) aus.
. Wählen Sie im linken Navigationsbereich des SCV *Dashboard* > *Status*.
. Zeigen Sie eine Übersicht Statusinformationen an, oder klicken Sie auf einen Link, um weitere Informationen zu erhalten, wie in der folgenden Tabelle aufgeführt.
+
|===
| Dieses Dashboard-Feld… | Zeigt die folgenden Informationen an… 


 a| 
Zuletzt verwendete Job-Aktivitäten
 a| 
Die drei bis fünf letzten Backup-, Restore- und Mount-Aufgaben.

** Klicken Sie auf eine Job-ID, um weitere Details zu diesem Job anzuzeigen.
** Klicken Sie auf *Alle anzeigen*, um zur Registerkarte Job Monitor zu gelangen, um weitere Details zu allen Jobs anzuzeigen.




 a| 
Jobs
 a| 
Eine Anzahl von Jobs (Backup, Restore und Mount), die innerhalb des ausgewählten Zeitfensters ausgeführt werden. Bewegen Sie den Cursor über einen Abschnitt des Diagramms, um weitere Details zu dieser Kategorie anzuzeigen.



 a| 
Aktuelle Zusammenfassung Des Schutzes
 a| 
Zusammenfassungen des Datensicherungsstatus von primären und sekundären VMs oder Datastores im ausgewählten Zeitfenster.

** Klicken Sie auf das Dropdown-Menü, um *VMs* oder *Datastores* auszuwählen.
** Wählen Sie als Sekundärspeicher *SnapVault* oder *SnapMirror* aus.
** Bewegen Sie den Mauszeiger über einen Abschnitt eines Diagramms, um die Anzahl der VMs oder Datastores in dieser Kategorie anzuzeigen. In der Kategorie erfolgreich wird für jede Ressource das aktuellste Backup aufgeführt.
** Sie können das Zeitfenster ändern, indem Sie die Konfigurationsdatei bearbeiten. Der Standardwert ist 7 Tage. Weitere Informationen finden Sie unter link:scpivs44_customize_your_configuration.html["Passen Sie Ihre Konfiguration an"].
** Interne Zähler werden nach jedem primären oder sekundären Backup aktualisiert. Die Dashboard-Kachel wird alle sechs Stunden aktualisiert. Die Aktualisierungszeit kann nicht geändert werden. Hinweis: Wenn Sie eine Mirror-Vault-Schutzrichtlinie verwenden, werden die Zähler für die Sicherungszusammenfassung im SnapVault-Übersichtsdiagramm und nicht im SnapMirror Diagramm angezeigt.




 a| 
Konfiguration
 a| 
Gesamtzahl der jeden Objekttyp, die vom SnapCenter Plug-in für VMware vSphere gemanagt wird



 a| 
Storage
 a| 
Die Gesamtzahl der erstellten Snapshots, SnapVault- und SnapMirror-Snapshots sowie die Menge des für primäre und sekundäre Snapshots verwendeten Speichers. Das Liniendiagramm stellt den primären und sekundären Speicherverbrauch über einen laufenden Zeitraum von 90 Tagen täglich separat dar. Storage-Informationen werden alle 24 Stunden um 1:08 UHR aktualisiert. Storage Savings ist das Verhältnis der logischen Kapazität (Snapshot-Einsparungen plus verbrauchter Storage) zur physischen Kapazität des primären Storage. Das Balkendiagramm zeigt die Storage-Einsparungen.

Bewegen Sie den Cursor über eine Linie auf der Karte, um detaillierte Ergebnisse für Tag anzuzeigen.

|===

