---
sidebar: sidebar 
permalink: scpivs44_deploy_snapcenter_plug-in_for_vmware_vsphere.html 
keywords:  
summary: Um SnapCenter VMs, Datastores und applikationskonsistente Datenbanken auf virtualisierten Maschinen zu sichern, müssen Sie das SnapCenter Plug-in für VMware vSphere implementieren. 
---
= Implementieren Sie das SnapCenter Plug-in für VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Um SnapCenter VMs, Datastores und applikationskonsistente Datenbanken auf virtualisierten Maschinen zu sichern, müssen Sie das SnapCenter Plug-in für VMware vSphere implementieren.

.Bevor Sie beginnen
In diesem Abschnitt werden alle erforderlichen Aktionen aufgeführt, die Sie vor Beginn der Bereitstellung durchführen sollten.


NOTE:  Die OVA-Implementierung wird in VMware vCenter 7u1 und höher unterstützt.

* Sie müssen die Implementierungsanforderungen gelesen haben.
* Sie müssen eine unterstützte Version von vCenter Server ausführen.
* Sie müssen Ihre vCenter Server-Umgebung konfiguriert und eingerichtet haben.
* Sie müssen einen ESXi-Host für das SnapCenter-Plug-in für VMware vSphere VM eingerichtet haben.
* Sie müssen das SnapCenter-Plug-in für die VMware vSphere .tar-Datei heruntergeladen haben.
* Sie benötigen die Anmeldedaten für Ihre vCenter Server-Instanz.
* Sie müssen über ein Zertifikat mit gültigen öffentlichen und privaten Schlüssel-Dateien verfügen. Weitere Informationen finden Sie in den Artikeln unter https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_Certificate_Resolution_Guide["Storage-Zertifikatmanagement"] Abschnitt.
* Sie müssen alle Browser-Sitzungen des vSphere-Clients abgemeldet und geschlossen haben und den Browser-Cache gelöscht haben, um Probleme mit dem Browser-Cache während der Bereitstellung des SnapCenter-Plug-ins für VMware vSphere zu vermeiden.
* In vCenter müssen Sie Transport Layer Security (TLS) aktivieren. Lesen Sie die VMware-Dokumentation.
* Wenn Sie in anderen vCenter-Zentren als dem SnapCenter-Plug-in für VMware vSphere Backups durchführen möchten, müssen der ESXi-Server, das SnapCenter-Plug-in für VMware vSphere und jedes vCenter zur gleichen Zeit synchronisiert werden.
* Um VMs auf vVol Datastores zu schützen, müssen Sie zuerst ONTAP Tools für VMware vSphere implementieren. Aktuelle Informationen zu unterstützten Versionen von ONTAP-Tools finden Sie unter https://imt.netapp.com/matrix/imt.jsp?components=121034;&solution=1517&isHWU&src=IMT["NetApp Interoperabilitäts-Matrix-Tool"^]. Durch die ONTAP Tools wird Storage auf ONTAP und im VMware Web-Client bereitgestellt und konfiguriert.


Stellen Sie das SnapCenter-Plug-in für VMware vSphere in derselben Zeitzone wie vCenter bereit. Backup-Zeitpläne werden in der Zeitzone ausgeführt, in der das SnapCenter Plug-in für VMware vSphere bereitgestellt wird. VCenter meldet Daten in der Zeitzone, in der sich vCenter befindet. Wenn sich das SnapCenter-Plug-in für VMware vSphere und vCenter daher in unterschiedlichen Zeitzonen befinden, sind die Daten im SnapCenter-Plug-in für VMware vSphere Dashboard möglicherweise nicht mit den Daten in den Berichten identisch.

.Schritte
. Befolgen Sie für VMware vCenter 7.0.3 und neuere Versionen die Schritte unter link:scpivs44_download_the_ova_open_virtual_appliance.html["Open Virtual Appliance (OVA) herunterladen"^] So importieren Sie die Zertifikate in vCenter.
. Navigieren Sie in Ihrem Browser zu VMware vSphere vCenter.
+

NOTE: Für IPv6-Adressen-HTML-Web-Clients müssen Sie entweder Chrome oder Firefox verwenden.

. Melden Sie sich auf der Seite *VMware vCenter Single Sign-On* an.
. Klicken Sie im Navigationsfenster mit der rechten Maustaste auf ein Inventarobjekt, das ein gültiges übergeordnetes Objekt einer virtuellen Maschine ist, z. B. ein Rechenzentrum, Cluster oder Host, und wählen Sie *Deploy OVF Template* aus, um den VMware Deploy Wizard zu starten.
. Extrahieren Sie die .tar-Datei, die die .ova-Datei auf Ihr lokales System enthält. Geben Sie auf der Seite *Wählen Sie eine OVF-Vorlage* den Speicherort des an `.ova` Datei im extrahierten Ordner .tar.
. Klicken Sie Auf *Weiter*.
. Geben Sie auf der Seite *Name und Ordner* einen eindeutigen Namen für die VM oder vApp ein, und wählen Sie einen Speicherort für die Bereitstellung aus, und klicken Sie dann auf *Weiter*.
+
In diesem Schritt wird festgelegt, wo der importiert werden soll `.tar` Datei in vCenter. Der Standardname für die VM entspricht dem Namen der ausgewählten `.ova` Datei: Wenn Sie den Standardnamen ändern, wählen Sie einen Namen aus, der in jedem vCenter Server VM-Ordner eindeutig ist.

+
Der Standardbereitstellungs-Speicherort für die VM ist das Inventurobjekt, an dem Sie den Assistenten gestartet haben.

. Wählen Sie auf der Seite *Select a Resource* die Ressource aus, auf der Sie die bereitgestellte VM-Vorlage ausführen möchten, und klicken Sie auf *Next*.
. Überprüfen Sie auf der Seite * Details* die `.tar` Vorlagendetails und klicken Sie auf *Weiter*.
. Aktivieren Sie auf der Seite *Lizenzvereinbarungen* das Kontrollkästchen für *Ich akzeptiere alle Lizenzvereinbarungen*.
. Legen Sie auf der Seite * Storage auswählen* fest, wo und wie die Dateien für die bereitgestellte OVF-Vorlage gespeichert werden sollen.
+
.. Wählen Sie das Festplattenformat für die VMDKs aus.
.. Wählen Sie eine VM-Speicherrichtlinie aus.
+
Diese Option ist nur verfügbar, wenn Storage-Richtlinien auf der Zielressource aktiviert sind.

.. Wählen Sie einen Datenspeicher aus, um die implementierte OVA-Vorlage zu speichern.
+
Die Konfigurationsdatei und die Dateien virtueller Laufwerke werden auf dem Datastore gespeichert.

+
Wählen Sie einen Datenspeicher aus, der ausreichend groß ist, um die virtuelle Maschine oder vApp und alle zugehörigen virtuellen Festplattendateien aufzunehmen.



. Gehen Sie auf der Seite *Netzwerke auswählen* wie folgt vor:
+
.. Wählen Sie ein Quellnetzwerk aus, und ordnen Sie es einem Zielnetzwerk zu.
+
In der Spalte Source Network werden alle Netzwerke aufgelistet, die in der OVA-Vorlage definiert sind.

.. Wählen Sie im Abschnitt *IP Allocation Settings* das gewünschte IP-Adressenprotokoll aus und klicken Sie dann auf *Weiter*.
+
Das SnapCenter Plug-in für VMware vSphere unterstützt eine Netzwerkschnittstelle. Wenn Sie mehrere Netzwerkadapter benötigen, müssen Sie diese manuell einrichten. Siehe https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_create_additional_network_adapters_in_NDB_and_SCV_4.3["KB-Artikel: So erstellen Sie zusätzliche Netzwerkadapter"^].



. Gehen Sie auf der Seite *Vorlage anpassen* wie folgt vor:
+
.. Geben Sie im Abschnitt *Registrieren bei vorhandenem vCenter* den vCenter-Namen und die vCenter-Anmeldedaten der virtuellen Appliance ein.
+
Geben Sie im Feld *vCenter Benutzername* den Benutzernamen in das Format ein `domain\username`.

.. Geben Sie im Abschnitt *SCV-Anmeldeinformationen erstellen* die lokalen Anmeldeinformationen ein.
+
Geben Sie im Feld *Benutzername* den lokalen Benutzernamen ein; fügen Sie keine Domain-Details ein.

+

IMPORTANT: Notieren Sie sich den Benutzernamen und das Kennwort, den Sie angeben. Sie müssen diese Anmeldeinformationen verwenden, wenn Sie die Konfiguration des SnapCenter-Plug-ins für VMware vSphere später ändern möchten.

.. Geben Sie die Anmeldeinformationen für den Benutzer von maint ein.
.. Geben Sie im Abschnitt *Netzwerkeigenschaften einrichten* den Hostnamen ein.
+
... Geben Sie im Abschnitt *Setup IPv4 Network Properties* die Netzwerkinformationen wie IPv4-Adresse, IPv4-Netzmaske, IPv4-Gateway, primärer IPv4-DNS, sekundärer IPv4-DNS, und IPv4-Suchdomänen.
... Geben Sie im Abschnitt *IPv6-Netzwerkeigenschaften einrichten* die Netzwerkinformationen ein, z. B. IPv6-Adresse, IPv6-Netzmaske, IPv6-Gateway, IPv6-Primärer DNS, IPv6-SekundärDNS, und IPv6-Suchdomänen.
+
Wählen Sie die IPv4- oder IPv6-Adressfelder oder beide aus. Wenn Sie sowohl IPv4- als auch IPv6-Adressen verwenden, müssen Sie den primären DNS nur für eine dieser Adressen angeben.

+

IMPORTANT: Sie können diese Schritte überspringen und die Einträge im Abschnitt *Setup Network Properties* leer lassen, wenn Sie DHCP als Netzwerkkonfiguration verwenden möchten.



.. Wählen Sie unter *Setup Datum und Uhrzeit* die Zeitzone aus, in der sich das vCenter befindet.


. Überprüfen Sie die Seite auf der Seite *Ready to Complete* und klicken Sie auf *Finish*.
+
Alle Hosts müssen mit IP-Adressen konfiguriert sein (FQDN-Hostnamen werden nicht unterstützt). Der Bereitstellungsvorgang überprüft Ihre Eingaben vor der Bereitstellung nicht.

+
Sie können den Fortschritt der Bereitstellung im Fenster „Letzte Aufgaben“ anzeigen, während Sie warten, bis die OVF-Import- und Bereitstellungsaufgaben abgeschlossen sind.

+
Wenn das SnapCenter-Plug-in für VMware vSphere erfolgreich bereitgestellt wurde, wird es als Linux-VM bereitgestellt, bei vCenter registriert und ein VMware vSphere-Client installiert.

. Navigieren Sie zu der VM, auf der das SnapCenter-Plug-in für VMware vSphere bereitgestellt wurde, klicken Sie dann auf die Registerkarte *Zusammenfassung*, und klicken Sie dann auf das Feld *Einschalten*, um die virtuelle Appliance zu starten.
. Während das SnapCenter-Plug-in für VMware vSphere eingeschaltet ist, klicken Sie mit der rechten Maustaste auf das bereitgestellte SnapCenter-Plug-in für VMware vSphere, wählen Sie *Gastbetriebssystem* aus und klicken Sie dann auf *VMware-Tools installieren*.
+
Die VMware-Tools werden auf der VM installiert, auf der das SnapCenter-Plug-in für VMware vSphere bereitgestellt wird. Weitere Informationen zum Installieren von VMware-Tools finden Sie in der VMware-Dokumentation.

+
Die Implementierung kann einige Minuten dauern. Die erfolgreiche Bereitstellung wird angezeigt, wenn das SnapCenter-Plug-in für VMware vSphere eingeschaltet ist, die VMware-Tools installiert sind und Sie auf dem Bildschirm aufgefordert werden, sich beim SnapCenter-Plug-in für VMware vSphere anzumelden. Sie können die Netzwerkkonfiguration während des ersten Neustarts von DHCP auf statisch umschalten. Der Wechsel von statischem zu DHCP wird jedoch nicht unterstützt.

+
Auf dem Bildschirm wird die IP-Adresse angezeigt, an der das SnapCenter-Plug-in für VMware vSphere bereitgestellt wird. Notieren Sie sich die IP-Adresse. Sie müssen sich bei der SnapCenter-Plug-in für VMware vSphere-Management-GUI anmelden, wenn Sie Änderungen an der Konfiguration des SnapCenter-Plug-ins für VMware vSphere vornehmen möchten.

. Melden Sie sich mit der auf dem Bereitstellungsbildschirm angezeigten IP-Adresse und den im Bereitstellungsassistenten angegebenen Anmeldeinformationen bei der SnapCenter-Plug-in für VMware vSphere-VerwaltungsGUI an. überprüfen Sie dann im Dashboard, ob das SnapCenter-Plug-in für VMware vSphere erfolgreich mit vCenter verbunden und aktiviert ist.
+
Verwenden Sie das Format `\https://<appliance-IP-address>:8080` Um auf die Management-GUI zuzugreifen.

+
Melden Sie sich bei der Implementierung mit dem Admin-Benutzernamen und -Passwort an, und verwenden Sie das MFA-Token, das über die Wartungskonsole generiert wurde.

+
Wenn das SnapCenter-Plug-in für VMware vSphere nicht aktiviert ist, finden Sie weitere Informationen unter link:scpivs44_restart_the_vmware_vsphere_web_client_service.html["Starten Sie den VMware vSphere-Client-Service neu"].

+
Wenn der Hostname 'UnifiedVSC/SCV' lautet, starten Sie das Gerät neu. Wenn beim Neustart des Geräts der Hostname nicht in den angegebenen Hostnamen geändert wird, müssen Sie das Gerät neu installieren.



.Nachdem Sie fertig sind
Sie müssen die erforderlichen Daten ausfüllen link:scpivs44_post_deployment_required_operations_and_issues.html["Vorgänge nach der Implementierung"].
