---
sidebar: sidebar 
permalink: scpivs44_upgrade_to_a_new_patch.html 
keywords:  
summary: Wenn Sie ein Upgrade auf einen neuen Patch derselben Version durchführen, müssen Sie das SnapCenter Plug-in für VMware vSphere Cache auf dem vCenter Webserver löschen und den Server vor dem Upgrade oder der Registrierung neu starten. 
---
= Upgraden Sie auf einen neuen Patch derselben Version des SnapCenter Plug-ins für VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie ein Upgrade auf einen neuen Patch derselben Version durchführen, müssen Sie das SnapCenter Plug-in für VMware vSphere Cache auf dem vCenter Webserver löschen und den Server vor dem Upgrade oder der Registrierung neu starten.

Wenn der Plug-in-Cache nicht gelöscht wird, werden die letzten Jobs in den folgenden Szenarien nicht im Dashboard und auf der Jobüberwachung angezeigt:

* Das SnapCenter Plug-in für VMware vSphere wurde mithilfe von vCenter bereitgestellt und später auf ein Patch in derselben Version aktualisiert.
* Die virtuelle SnapCenter VMware Appliance wurde in vCenter 1 implementiert. Später wurde dieses SnapCenter Plug-in für VMware vSphere in einem neuen vCenter2 registriert. Eine neue Instanz des SnapCenter Plug-ins für VMware vSphere wird mit einem Patch erstellt und in vCenter1 registriert. Da vCenter1 jedoch noch das Cache-Plug-in des ersten SnapCenter Plug-ins für VMware vSphere ohne Patch hat, muss der Cache gelöscht werden.




== Schritte zum Löschen des Caches

. Suchen Sie das `vsphere-client-serenity` Ordner, und suchen Sie anschließend das `com.netapp.scv.client-<release-number>` Ordner und löschen.
+
Der Ordnername ändert sich für jedes Release.

+
Informationen zum Speicherort des Ordners für Ihr Betriebssystem finden Sie in der VMware-Dokumentation `vsphere-client-serenity` .

. Starten Sie vCenter Server neu.
+
Anschließend können Sie das SnapCenter-Plug-in für VMware vSphere aktualisieren.


