---
sidebar: sidebar 
permalink: scpivs44_rest_apis_fail_stuck_jobs.html 
keywords:  
summary: Um Job-IDs für VMware vSphere Web-Client-Jobs mit dem SnapCenter Plug-in für VMware vSphere REST-APIs zu finden, müssen SIE DIE REST-API-Aufrufe für VMware vSphere verwenden. 
---
= REST-API zum Markieren von eingeklemmten Jobs als fehlgeschlagen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Um Job-IDs für VMware vSphere Web-Client-Jobs mit dem SnapCenter Plug-in für VMware vSphere REST-APIs zu finden, müssen SIE DIE REST-API-Aufrufe für VMware vSphere verwenden. Diese REST-APIs wurden im SnapCenter Plug-in für VMware vSphere 4.4 hinzugefügt.

Fügen Sie für jede REST-API hinzu `https://<server>:<port>` An der Vorderseite der REST-API zu einem vollständigen Endpunkt

Verwenden Sie die folgende REST-API im Abschnitt Jobs, um Jobs zu ändern, die sich in einem laufenden Zustand befinden, in einen fehlgeschlagenen Status:

|===
| REST API | Kommentare 


| `/4.1/jobs/{id}/failJobs` | Wenn Sie die IDs von Jobs übergeben, die sich in einem laufenden Zustand befinden, `failJobs` Markiert diese Jobs als fehlgeschlagen. Um Jobs zu identifizieren, die sich in einem laufenden Zustand befinden, können Sie über die Job-Monitor-GUI den Status jedes Jobs und die Job-ID anzeigen. 
|===