---
sidebar: sidebar 
permalink: scpivs44_log_in_to_the_snapcenter_vmware_vsphere_web_client.html 
keywords:  
summary: Wenn das SnapCenter Plug-in für VMware vSphere bereitgestellt wird, wird ein VMware vSphere Web-Client in vCenter installiert, der zusammen mit anderen vSphere Web-Clients im vCenter-Bildschirm angezeigt wird. 
---
= Melden Sie sich beim SnapCenter VMware vSphere Web Client an
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn das SnapCenter Plug-in für VMware vSphere bereitgestellt wird, wird ein VMware vSphere Web-Client in vCenter installiert, der zusammen mit anderen vSphere Web-Clients im vCenter-Bildschirm angezeigt wird.

Transport Layer Security (TLS) muss in vCenter aktiviert sein. Lesen Sie die VMware-Dokumentation.

.Schritte
. Navigieren Sie in Ihrem Browser zu VMware vSphere vCenter.
. Klicken Sie auf dem VMware-Bildschirm *auf vSphere Client (HTML5)*.
. Melden Sie sich auf der Seite *VMware vCenter Single Sign-On* an.
+

IMPORTANT: Klicken Sie auf die Schaltfläche *Login*. Aufgrund eines bekannten VMware-Problems verwenden Sie den EINKABETASCHLÜSSEL nicht zur Anmeldung. Weitere Informationen finden Sie in der Dokumentation zu Problemen mit dem ESXi Embedded Host Client.

. Klicken Sie auf der Seite *VMware vSphere Web Client* in der Symbolleiste auf Menü und wählen Sie dann *SnapCenter Plug-in für VMware vSphere*.

