---
sidebar: sidebar 
permalink: scpivs44_deploy_snapcenter_plug-in_for_vmware_vsphere.html 
keywords:  
summary: Um SnapCenter VMs, Datastores und applikationskonsistente Datenbanken auf virtualisierten Maschinen zu sichern, müssen Sie das SnapCenter Plug-in für VMware vSphere implementieren. 
---
= Implementieren Sie das SnapCenter Plug-in für VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Um SnapCenter VMs, Datastores und applikationskonsistente Datenbanken auf virtualisierten Maschinen zu sichern, müssen Sie das SnapCenter Plug-in für VMware vSphere implementieren.

.Bevor Sie beginnen
* Sie müssen die Implementierungsanforderungen gelesen haben.
+
Der Bereitstellungsassistent überprüft nicht die Speicherplatzanforderungen. Wenn Sie nicht über genügend Speicherplatz auf dem Datastore verfügen, wird die Bereitstellung möglicherweise erfolgreich ausgeführt, die virtuelle Appliance wird jedoch nicht gestartet.

* Sie müssen eine unterstützte Version von vCenter Server ausführen.
* Sie müssen Ihre vCenter Server-Umgebung konfiguriert und eingerichtet haben.
* Sie müssen einen ESXi-Host für die SnapCenter-VMware-Plug-in-VM einrichten.
* Sie müssen das SnapCenter-Plug-in für die Datei VMware vSphere .ova heruntergeladen haben.
* Sie müssen über die Anmeldeinformationen für Ihre vCenter Server-Instanz verfügen.
* Sie müssen alle Browser-Sitzungen des vSphere Web Clients abgemeldet und geschlossen haben und den Browser-Cache gelöscht haben, um Probleme mit dem Browser-Cache während der Bereitstellung des SnapCenter VMware Plug-ins zu vermeiden.
* In vCenter müssen Sie Transport Layer Security (TLS) aktivieren. Lesen Sie die VMware-Dokumentation.
* Sie können das SnapCenter VMware Plug-in im selben vCenter bereitstellen wie die virtuelle Appliance für VSC 7.x und höher.
* Wenn Sie in anderen vCenter als in einem SnapCenter VMware Plug-in Backups durchführen möchten, müssen der ESXi Server, das SnapCenter VMware Plug-in und jedes vCenter mit derselben Zeit synchronisiert werden.
* Um VMs auf vVol Datastores zu schützen, müssen Sie zuerst ONTAP Tools für VMware vSphere implementieren. Mit den ONTAP Tools können Storage auf ONTAP und im VMware Web-Client bereitgestellt und konfiguriert werden.


Implementieren Sie das SnapCenter VMware Plug-in in derselben Zeitzone wie vCenter. Backup-Zeitpläne werden in der Zeitzone ausgeführt, in der das SnapCenter VMware Plug-in implementiert wird. VCenter meldet Daten in der Zeitzone, in der sich die vCenter befindet. Wenn sich das SnapCenter VMware Plug-in und vCenter in verschiedenen Zeitzonen befinden, sind die Daten im SnapCenter VMware Plug-in Dashboard möglicherweise nicht mit den Daten in den Berichten identisch.

.Schritte
. Navigieren Sie in Ihrem Browser zu VMware vSphere vCenter.
+

NOTE: Für IPv6 HTML-Webclients müssen Sie entweder Chrome oder Firefox verwenden.

. Klicken Sie auf dem VMware-Bildschirm auf *vSphere Web Client (HTML5)*.
. Melden Sie sich auf der Seite *VMware vCenter Single Sign-On* an.
. Klicken Sie im Navigator-Fenster mit der rechten Maustaste auf ein Inventory-Objekt, das ein gültiges übergeordnetes Objekt einer virtuellen Maschine ist, z. B. ein Rechenzentrum, Cluster oder Host, und wählen Sie *OVF-Vorlage bereitstellen* aus, um den VMware Deploy Wizard zu starten.
. Geben Sie auf der Seite *Wählen Sie eine OVF-Vorlage* den Speicherort des an `.ova` Datei (wie in der folgenden Tabelle dargestellt) und klicken Sie auf *Weiter*.
+
|===
| Wenn Sie das heruntergeladen haben `.ova` Datei zu… | Do this… 


| Ein Internetstandort | Geben Sie die URL ein. Unterstützte URL-Quellen sind HTTP und HTTPS. 


| Eine lokale Datei | Klicken Sie auf *Wählen Sie Dateien* und navigieren Sie zur .ova-Datei. 
|===
. Geben Sie auf der Seite *Name und Ordner* einen eindeutigen Namen für die VM oder vApp ein, und wählen Sie einen Speicherort für die Bereitstellung aus, und klicken Sie dann auf *Weiter*.
+
In diesem Schritt wird festgelegt, wo der importiert werden soll `.ova` Datei in vCenter. Der Standardname für die VM entspricht dem Namen der ausgewählten `.ova` Datei: Wenn Sie den Standardnamen ändern, wählen Sie einen Namen aus, der in jedem vCenter Server VM-Ordner eindeutig ist.

+
Der Standardbereitstellungs-Speicherort für die VM ist das Inventurobjekt, an dem Sie den Assistenten gestartet haben.

. Wählen Sie auf der Seite *Select a Resource* die Ressource aus, auf der Sie die bereitgestellte VM-Vorlage ausführen möchten, und klicken Sie auf *Next*.
. Überprüfen Sie auf der Seite * Details* die `.ova` Vorlagendetails und klicken Sie auf *Weiter*.
. Aktivieren Sie auf der Seite *Lizenzvereinbarungen* das Kontrollkästchen für *Ich akzeptiere alle Lizenzvereinbarungen*.
. Legen Sie auf der Seite * Storage auswählen* fest, wo und wie die Dateien für die bereitgestellte OVF-Vorlage gespeichert werden sollen.
+
.. Wählen Sie das Festplattenformat für die VMDKs aus.
.. Wählen Sie eine VM-Speicherrichtlinie aus.
+
Diese Option ist nur verfügbar, wenn Storage-Richtlinien auf der Zielressource aktiviert sind.

.. Wählen Sie einen Datenspeicher aus, um die implementierte OVA-Vorlage zu speichern.
+
Die Konfigurationsdatei und die Dateien virtueller Laufwerke werden auf dem Datastore gespeichert.

+
Wählen Sie einen Datenspeicher aus, der ausreichend groß ist, um die virtuelle Maschine oder vApp und alle zugehörigen virtuellen Festplattendateien aufzunehmen.



. Gehen Sie auf der Seite *Netzwerke auswählen* wie folgt vor:
+
.. Wählen Sie ein Quellnetzwerk aus, und ordnen Sie es einem Zielnetzwerk zu.
+
In der Spalte Source Network werden alle Netzwerke aufgelistet, die in der OVA-Vorlage definiert sind.

.. Wählen Sie im Abschnitt *IP-Zuweisungs-Einstellungen* das erforderliche IP-Protokoll aus und klicken Sie dann auf *Weiter*.
+
Das SnapCenter Plug-in für VMware vSphere unterstützt eine Netzwerkschnittstelle. Wenn Sie mehrere Netzwerkadapter benötigen, müssen Sie diese manuell einrichten. Siehe https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_create_additional_network_adapters_in_NDB_and_SCV_4.3["KB-Artikel: So erstellen Sie zusätzliche Netzwerkadapter"^].



. Gehen Sie auf der Seite *Vorlage anpassen* wie folgt vor:
+
.. Geben Sie im Abschnitt *Registrieren bei vorhandenem vCenter* den vCenter-Namen und die vCenter-Anmeldedaten der virtuellen Appliance ein.
+
Geben Sie im Feld *vCenter Benutzername* den Benutzernamen in das Format ein `domain\username`.

.. Geben Sie im Abschnitt *SCV-Anmeldeinformationen erstellen* die lokalen Anmeldeinformationen ein.
+
Geben Sie im Feld *Benutzername* den lokalen Benutzernamen ein; fügen Sie keine Domain-Details ein.

+

IMPORTANT: Notieren Sie sich den Benutzernamen und das Kennwort, den Sie angeben. Sie müssen diese Anmeldedaten verwenden, wenn Sie die SnapCenter VMware Plug-in-Konfiguration später ändern möchten.

.. Geben Sie unter *Setup-Netzwerkeigenschaften* den Hostnamen ein.
+
... Geben Sie im Abschnitt * Setup IPv4 Network Properties* die Netzwerkinformationen ein, z. B. IPv4-Adresse, IPv4-Netzmaske, IPv4-Gateway, IPv4 Primary DNS, IPv4 Secondary DNS, Und IPv4-Suchdomänen.
... Geben Sie im Abschnitt * IPv6-Netzwerkeigenschaften* die Netzwerkinformationen ein, z. B. die IPv6-Adresse, IPv6-Netzmaske, IPv6 Gateway, IPv6 Primary DNS, IPv6 Secondary DNS, Und IPv6-Suchdomänen.
+
Wählen Sie gegebenenfalls die IPv4- und/oder IPv6-Felder aus. Wenn Sie sowohl IPv4 als auch IPv6 verwenden, müssen Sie den primären DNS nur für eine von ihnen angeben.

+

IMPORTANT: Sie können diese Schritte überspringen und die Einträge im Abschnitt *Setup Network Properties* leer lassen, wenn Sie DHCP als Netzwerkkonfiguration verwenden möchten.



.. Wählen Sie unter *Setup Datum und Uhrzeit* die Zeitzone aus, in der sich das vCenter befindet.


. Überprüfen Sie die Seite auf der Seite *Ready to Complete* und klicken Sie auf *Finish*.
+
Alle Hosts müssen mit IP-Adressen konfiguriert sein (FQDN-Hostnamen werden nicht unterstützt). Der Bereitstellungsvorgang überprüft Ihre Eingaben vor der Bereitstellung nicht.

+
Sie können den Fortschritt der Bereitstellung im Fenster „Letzte Aufgaben“ anzeigen, während Sie warten, bis die OVF-Import- und Bereitstellungsaufgaben abgeschlossen sind.

+
Wenn das SnapCenter VMware Plug-in erfolgreich implementiert wird, wird es als Linux VM, mit vCenter registriert und ein VMware vSphere Web-Client installiert.

. Navigieren Sie zu der VM, auf der das SnapCenter-VMware-Plug-in bereitgestellt wurde, und klicken Sie dann auf die Registerkarte *Zusammenfassung* und dann auf das Feld *Einschalten*, um die virtuelle Appliance zu starten.
. Während das SnapCenter VMware Plug-in eingeschaltet ist, klicken Sie mit der rechten Maustaste auf das implementierte SnapCenter VMware Plug-in, wählen Sie *Gastbetriebssystem* aus und klicken Sie dann auf *VMware Tools installieren*.
+
Die VMware Tools werden auf der VM installiert, auf der das SnapCenter VMware Plug-in bereitgestellt wird. Weitere Informationen zum Installieren von VMware-Tools finden Sie in der VMware-Dokumentation.

+
Die Implementierung kann einige Minuten dauern. Eine erfolgreiche Implementierung wird angezeigt, wenn das SnapCenter VMware Plug-in eingeschaltet ist, die VMware-Tools installiert sind und Sie auf dem Bildschirm zur Anmeldung beim SnapCenter VMware Plug-in aufgefordert werden. Sie können die Netzwerkkonfiguration während des ersten Neustarts von DHCP auf statisch umschalten. Der Wechsel von statischem zu DHCP wird jedoch nicht unterstützt.

+
Auf dem Bildschirm wird die IP-Adresse angezeigt, an der das SnapCenter-VMware-Plug-in bereitgestellt wird. Notieren Sie sich die IP-Adresse. Sie müssen sich bei der Management-GUI des SnapCenter VMware Plug-ins anmelden, um Änderungen an der SnapCenter VMware Plug-in-Konfiguration vorzunehmen.

. Melden Sie sich mithilfe der im Implementierungsbildschirm angezeigten IP-Adresse bei der Management-GUI des SnapCenter VMware-Plug-ins an und überprüfen Sie im Dashboard, ob das SnapCenter VMware-Plug-in erfolgreich mit vCenter verbunden und aktiviert ist.
+
Verwenden Sie das Format `https://<appliance-IP-address>:8080` Um auf die Management-GUI zuzugreifen.

+
Standardmäßig wird der Benutzername der Wartungskonsole auf „maint“ gesetzt und das Passwort auf „admin123“ gesetzt.

+
Wenn das SnapCenter VMware Plug-in nicht aktiviert ist, lesen Sie link:scpivs44_restart_the_vmware_vsphere_web_client_service.html["Starten Sie den VMware vSphere Web-Client-Service neu"].

+
Wenn der Hostname 'UnifiedVSC/SCV' lautet, starten Sie das Gerät neu. Wenn beim Neustart des Geräts der Hostname nicht in den angegebenen Hostnamen geändert wird, müssen Sie das Gerät neu installieren.



Sie müssen die erforderlichen Daten ausfüllen link:scpivs44_post_deployment_required_operations_and_issues.html["Vorgänge nach der Implementierung"].
