---
sidebar: sidebar 
permalink: scpivs44_restore_a_specific_backup_of_the_mysql_database.html 
keywords:  
summary: 'Mit der Wartungskonsole können Sie ein bestimmtes Backup der MySQL-Datenbank (auch als NSM-Datenbank bezeichnet) für das SnapCenter Plug-in für die virtuelle Appliance VMware vSphere wiederherstellen.' 
---
= Stellen Sie ein bestimmtes Backup der MySQL-Datenbank wieder her
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Mit der Wartungskonsole können Sie ein bestimmtes Backup der MySQL-Datenbank (auch als NSM-Datenbank bezeichnet) für das SnapCenter Plug-in für die virtuelle Appliance VMware vSphere wiederherstellen.

.Schritte
. Öffnen Sie ein Fenster der Wartungskonsole.
+
link:scpivs44_manage_snapcenter_plug-in_for_vmware_vsphere.html#access-the-maintenance-console["Öffnen Sie die Wartungskonsole"].

. Geben Sie im Hauptmenü die Option *1) Anwendungskonfiguration* ein.
. Geben Sie im Menü Anwendungskonfiguration die Option *6) MySQL-Sicherung und -Wiederherstellung* ein.
. Geben Sie im Menü MySQL Backup and Restore Configuration die Option *2) MySQL-Backups* ein und notieren Sie sich dann das Backup, das Sie wiederherstellen möchten.
. Geben Sie im Menü MySQL Backup and Restore Configuration die Option *3) MySQL Backup wiederherstellen* ein.
. Geben Sie an der Eingabeaufforderung „Wiederherstellen mit dem neuesten Backup“ *n* ein.
. Geben Sie an der Eingabeaufforderung „Backup to restore from“ den Sicherungsnamen ein, und drücken Sie dann *Enter*.
+
Die ausgewählte MySQL-Backup-Datenbank wird an ihren ursprünglichen Speicherort wiederhergestellt.


