---
sidebar: sidebar 
permalink: scpivs44_extend_the_time_of_a_guest_file_restore_session.html 
keywords:  
summary: Standardmäßig ist eine angeschlossene Gastdatei-Wiederherstellung VMDK für 24 Stunden verfügbar und wird automatisch getrennt. Sie können die Zeit auf der Seite Gastkonfiguration verlängern. 
---
= Verlängern Sie die Zeit für die Wiederherstellung von Gastdateien
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Standardmäßig ist eine angeschlossene Gastdatei-Wiederherstellung VMDK für 24 Stunden verfügbar und wird automatisch getrennt. Sie können die Zeit auf der Seite *Gastkonfiguration* verlängern.

Es ist vielleicht möglich, eine Wiederherstellungssitzung für Gastdateien zu erweitern, wenn Sie zu einem späteren Zeitpunkt zusätzliche Dateien oder Ordner aus der beigefügten VMDK wiederherstellen möchten. Da allerdings für die Wiederherstellung von Gastdateien viele Ressourcen verwendet werden, sollte die Sitzungsdauer nur gelegentlich verlängert werden.

.Schritte
. Klicken Sie im VMware vSphere Web-Client auf *Wiederherstellung der Gastdatei*.
. Wählen Sie eine Gastdatei-Wiederherstellungssitzung aus, und klicken Sie in der Titelleiste des Gastsession-Monitors auf das Symbol Ausgewählte Gastsitzung erweitern.
+
Die Sitzung wird um weitere 24 Stunden verlängert.


