---
sidebar: sidebar 
permalink: scpivs44_download_job_logs.html 
keywords:  
summary: Sie können die Jobprotokolle von der Registerkarte Job Monitor auf dem Dashboard des SnapCenter VMware vSphere Clients herunterladen. 
---
= Job-Protokolle herunterladen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können die Jobprotokolle von der Registerkarte Job Monitor auf dem Dashboard des SnapCenter VMware vSphere Clients herunterladen.

Wenn bei der Verwendung des VMware vSphere-Clients ein unerwartetes Verhalten auftritt, können Sie mithilfe der Protokolldateien die Ursache identifizieren und das Problem lösen.


NOTE: Der Standardwert für die Aufbewahrung von Jobprotokollen beträgt 30 Tage; der Standardwert für die Beibehaltung von Jobs beträgt 90 Tage. Job-Protokolle und Jobs, die älter als die konfigurierte Aufbewahrung sind, werden alle sechs Stunden gelöscht. Sie können die Konfiguration verwenden `jobs/cleanup` REST-APIs ändern, wie lange Jobs und Job-Logs aufbewahrt werden. Der Spülzeitplan kann nicht geändert werden.

.Schritte
. Wählen Sie auf der Verknüpfungsseite des vCenter-Clients die Option SnapCenter-Plug-in für VMware vSphere (SCV) aus.
. Wählen Sie im linken Navigationsbereich des SCV *Dashboard* > *Job Monitor*.
. Wählen Sie in der Titelleiste des Job Monitors das Download-Symbol aus.
+
Möglicherweise müssen Sie nach rechts blättern, um das Symbol zu sehen.

+
Sie können auch auf einen Job doppelklicken, um auf das Fenster Job Details zuzugreifen und dann auf *Job Logs herunterladen* klicken.



.Ergebnis
Job-Protokolle befinden sich auf dem Linux VM-Host, auf dem das SnapCenter Plug-in für VMware vSphere bereitgestellt wird. Der Standardspeicherort für das Jobprotokoll ist `/var/log/netapp`.

Wenn Sie versucht haben, Jobprotokolle herunterzuladen, aber die Protokolldatei mit dem Namen in der Fehlermeldung gelöscht wurde, kann es zu folgendem Fehler kommen: `HTTP ERROR 500 Problem accessing /export-scv-logs`. Um diesen Fehler zu beheben, überprüfen Sie den Zugriffsstatus und die Berechtigungen für die Datei mit dem Namen in der Fehlermeldung und beheben Sie das Zugriffsproblem.
