---
sidebar: sidebar 
permalink: scpivs44_restore_vmdks_from_backups.html 
keywords:  
summary: Sie können vorhandene VMDKs, gelöschte oder abgetrennte VMDKs, entweder von einem primären oder sekundären Backup herkömmlicher VMs oder vVol VMs wiederherstellen. 
---
= Wiederherstellung von VMDKs aus Backups
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können vorhandene VMDKs, gelöschte oder abgetrennte VMDKs, entweder von einem primären oder sekundären Backup herkömmlicher VMs oder vVol VMs wiederherstellen.

Sie können eine oder mehrere Virtual Machine-Festplatten (VMDKs) auf einer VM im selben Datenspeicher wiederherstellen.


TIP: Um die Performance von Restore-Vorgängen in NFS-Umgebungen zu verbessern, aktivieren Sie vStorage API for Array Integration (VAAI) für VMware Applikation.

.Bevor Sie beginnen
* Ein Backup muss vorhanden sein.
+
Sie müssen mit dem SnapCenter Plug-in für VMware vSphere eine Sicherung der VM erstellt haben.

* Die VM darf nicht während der Übertragung sein.
+
Die VM, die Sie wiederherstellen möchten, darf sich nicht in einem Zustand von vMotion oder Storage vMotion befinden.



.Über diese Aufgabe
* Wenn die VMDK gelöscht oder von der VM getrennt wird, wird die VMDK durch den Wiederherstellungsvorgang an die VM angeschlossen.
* Ein Wiederherstellungsvorgang kann fehlschlagen, wenn der Storage Tier der FabricPool, auf dem sich die VM befindet, nicht verfügbar ist.
* Verbinden Sie VMDKs über den Standard-SCSI-Controller und stellen Sie Wiederherstellungsvorgänge her. Wenn jedoch VMDKs gesichert werden, die an eine VM mit NVMe-Festplatte angeschlossen sind, verwenden die Anschluss- und Wiederherstellungsvorgänge, sofern verfügbar, den NVMe-Controller.


.Schritte
. Klicken Sie in der VMware vSphere-Client-GUI in der Symbolleiste auf *Menü* und wählen Sie dann in der Dropdown-Liste *VMs und Vorlagen* aus.
. Klicken Sie im linken Navigationsbereich mit der rechten Maustaste auf eine VM, wählen Sie dann *SnapCenter Plug-in für VMware vSphere* in der Dropdown-Liste aus, und wählen Sie dann *Wiederherstellen* in der sekundären Dropdown-Liste aus.
. Wählen Sie im Assistenten *Wiederherstellen* auf der Seite Sicherung auswählen die Sicherungskopie aus, aus der Sie die Sicherungskopie wiederherstellen möchten.
+
Sie können nach einem bestimmten Backup-Namen oder einem partiellen Backup-Namen suchen, oder Sie können die Backup-Liste filtern, indem Sie auf das Filtersymbol klicken und einen Datums- und Zeitbereich auswählen. Wählen Sie aus, ob Sie Backups mit VMware-Snapshots erstellen möchten, ob Sie gemountete Backups möchten. Und primären oder sekundären Standort. Klicken Sie auf *OK*, um zum Assistenten zurückzukehren.

. Wählen Sie auf der Seite *Bereich auswählen* das Wiederherstellungsziel aus.
+
|===
| Wiederherstellen auf… | Geben Sie das Wiederherstellungsziel… an 


| Den ursprünglichen Datenspeicher verwendet | Wählen Sie in der Dropdown-Liste * bestimmtes Laufwerk* aus und klicken Sie dann auf *Weiter*. In der Tabelle Datastore Selection können Sie beliebige VMDKs auswählen oder deren Auswahl aufheben. 


| Einen alternativen Datenspeicher an einem alternativen Speicherort | Klicken Sie auf den Ziel-Datastore und wählen Sie einen anderen Datastore aus der Liste aus. 
|===
. Wählen Sie auf der Seite *Speicherort auswählen* den Snapshot aus, den Sie wiederherstellen möchten (primär oder sekundär).
. Überprüfen Sie die Übersichtsseite und klicken Sie dann auf *Fertig stellen*.
. Optional: Überwachen Sie den Arbeitsfortschritt, indem Sie unten auf dem Bildschirm auf *Letzte Aufgaben* klicken.
. Aktualisieren Sie den Bildschirm, um aktualisierte Informationen anzuzeigen.

