---
sidebar: sidebar 
permalink: scpivs44_add_storage_01.html 
keywords:  
summary: Durch Hinzufügen von Storage kann das SnapCenter Plug-in für VMware vSphere Backup- und Restore-Vorgänge in vCenter erkennen und managen. 
---
= Erweitern Sie Ihren Storage
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Bevor Sie VMs sichern oder wiederherstellen können, müssen Sie Storage-Cluster oder Storage-VMs hinzufügen. Durch Hinzufügen von Storage kann das SnapCenter Plug-in für VMware vSphere Backup- und Restore-Vorgänge in vCenter erkennen und managen.

* Welche GUI verwendet werden soll
+
Verwenden Sie den VMware vSphere Client, um Storage hinzuzufügen.

* Große LUNs
+
Das SnapCenter Plug-in für VMware vSphere 4.5 und höher unterstützt Datastores mit großen LUN-Größen bis zu 128 TB auf ASA Aggregaten. Bei großen LUNs unterstützt SnapCenter nur über Thick Provisioning bereitgestellte LUNs, um Latenz zu vermeiden.

* VMware Virtual Volumes (VVols)
+
Sie müssen Storage-Cluster zum SnapCenter-Plug-in für VMware vSphere und ONTAP-Tools für VMware vSphere für vVol Data Protection hinzufügen, um arbeiten zu können.

+
Weitere Informationen finden Sie unter https://docs.netapp.com/vapp-98/index.jsp["ONTAP Tools für VMware vSphere"^]



.Bevor Sie beginnen
Der ESXi Server, das SnapCenter VMware Plug-in und jedes vCenter müssen zur gleichen Zeit synchronisiert werden. Wenn Sie versuchen, Speicher hinzuzufügen, aber die Zeiteinstellungen für Ihre vCenters nicht synchronisiert sind, schlägt der Vorgang möglicherweise mit einem Java-Zertifikatfehler fehl.

.Über diese Aufgabe
Das SnapCenter VMware Plug-in führt Backup- und Restore-Vorgänge auf direkt verbundenen Storage-VMs und auf Storage-VMs in einem Storage-Cluster aus.


NOTE: Wenn Sie das SnapCenter VMware Plug-in zur Unterstützung applikationsbasierter Backups auf VMDKs verwenden, müssen Sie über die Benutzeroberfläche von SnapCenter die Details zur Storage-Authentifizierung eingeben und die Speichersysteme registrieren.

* Bei vCenters im Linked-Modus müssen Sie jedem vCenter separat Storage-Systeme hinzufügen.
* Wenn Sie SVMs hinzufügen, müssen die Namen von Storage-VMs den Management-LIFs zugewiesen werden.
+
Wenn Sie in SnapCenter Einträge zur Datei „_etc\Hosts_“ für Storage-VM-Namen hinzugefügt haben, müssen Sie sicherstellen, dass diese auch von der virtuellen Appliance aufgelöst werden können. Wenn dies nicht der Fall ist, sollten Sie ähnliche Einträge zur _etc/Hosts_-Datei innerhalb der Appliance hinzufügen.

+
Wenn Sie eine Storage-VM mit einem Namen hinzufügen, der nicht zur Management-LIF auflöst, schlagen geplante Backup-Jobs fehl, da das Plug-in keine Datenspeicher oder Volumes auf dieser Storage-VM finden kann. Falls dies der Fall ist, fügen Sie entweder die Storage VM zur SnapCenter hinzu und geben Sie die Management-LIF an, oder fügen Sie einen Cluster hinzu, der die Storage-VM enthält, und geben Sie die Cluster-Management-LIF an.

* Details zur Storage-Authentifizierung werden nicht zwischen mehreren Instanzen des SnapCenter VMware Plug-ins oder zwischen Windows SnapCenter Server und dem SnapCenter Plug-in in in vCenter gemeinsam genutzt.


.Schritte
. Klicken Sie im linken Navigator-Bereich des vSphere-Clients auf *Storage Systems*.
. Wählen Sie auf der Seite Speichersysteme die Option *Hinzufügen* aus.
. Geben Sie im Assistenten * Storage System* die grundlegenden Speicher-VM oder Cluster-Informationen ein, wie in der folgenden Tabelle aufgeführt:
+
|===
| Für dieses Feld… | Do this… 


| Storage-System | Geben Sie die IP-Adresse eines Storage-Clusters oder einer Storage-VM des FQDN oder Management LIF ein.
Das SnapCenter VMware Plug-in unterstützt nicht mehrere Storage-VMs mit demselben Namen in verschiedenen Clustern. 


| Authentifizierungsmethode | Wählen Sie entweder Anmeldeinformationen oder Zertifikat aus. Es werden zwei Arten von Zertifikaten unterstützt: - https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_configure_a_CA_signed_certificate_for_storage_system_authentication_with_SCV["KANN signiertes Zertifikat"^]- https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_configure_a_self-signed_certificate_for_storage_system_authentication_with_SCV["Selbstsigniertes Zertifikat"^] 


| Benutzername | Dieses Feld wird angezeigt, wenn Sie Anmeldeinformationen als Authentifizierungsmethode auswählen. Geben Sie den ONTAP-Benutzernamen ein, mit dem Sie sich bei der Storage-VM oder beim Cluster anmelden. 


| Passwort | Dieses Feld wird angezeigt, wenn Sie Anmeldeinformationen als Authentifizierungsmethode auswählen. Geben Sie das Passwort für die Storage-VM oder das Cluster-Login ein. 


| Zertifikat | Dieses Feld wird angezeigt, wenn Sie Zertifikat als Authentifizierungsmethode auswählen. Wählen Sie die Zertifikatdatei aus. 


| Privater Schlüssel | Dieses Feld wird angezeigt, wenn Sie Zertifikat als Authentifizierungsmethode auswählen. Wählen Sie die Datei mit dem privaten Schlüssel aus. 


| Protokoll | Wählen Sie das Storage-Protokoll aus. 


| Port | Port, den das Speichersystem akzeptiert.
- 443 für HTTPS-Verbindung
- 80 für HTTP-Verbindung 


| Zeitüberschreitung | Geben Sie die Anzahl der Sekunden ein, die das SnapCenter-VMware-Plug-in warten soll, bevor Sie den Vorgang absetzen. Die Standardeinstellung ist 60 Sekunden. 


| Bevorzugte IP | Wenn die Storage VM über mehrere Management-IP-Adressen verfügt, aktivieren Sie dieses Kontrollkästchen und geben Sie die IP-Adresse ein, die das SnapCenter-VMware-Plug-in verwenden soll.
*Hinweis:* Verwenden Sie keine eckigen Klammern ([]), wenn Sie die IP-Adresse eingeben. 


| Einstellungen für Ereignismanagement-System (EMS) und AutoSupport | Wenn Sie EMS-Meldungen an das Syslog-Speichersystem senden möchten oder wenn Sie AutoSupport-Meldungen für den angewendeten Schutz, abgeschlossene Wiederherstellungsvorgänge oder fehlgeschlagene Vorgänge an das Speichersystem senden möchten, aktivieren Sie das entsprechende Kontrollkästchen. Aktivieren Sie das Kontrollkästchen *AutoSupport-Benachrichtigung für fehlgeschlagene Vorgänge an das Speichersystem senden* und das Kontrollkästchen * SnapCenter-Serverereignisse in syslog*, um AutoSupport-Benachrichtigungen zu aktivieren. 


| Protokollieren von SnapCenter-Serverereignissen im Syslog | Aktivieren Sie das Kontrollkästchen, um Ereignisse für das SnapCenter VMware Plug-in zu protokollieren. 


| AutoSupport-Benachrichtigung für fehlgeschlagenen Vorgang an das Speichersystem senden | Aktivieren Sie das Kontrollkästchen, wenn AutoSupport-Benachrichtigungen für fehlgeschlagene Datensicherungsaufträge angezeigt werden sollen. Sie müssen auch AutoSupport auf der Storage VM aktivieren und die AutoSupport E-Mail-Einstellungen konfigurieren. 
|===
. Klicken Sie Auf *Hinzufügen*.
+
Wenn Sie ein Storage-Cluster hinzugefügt haben, werden alle Storage-VMs in diesem Cluster automatisch hinzugefügt. Automatisch hinzugefügte Speicher-VMs (manchmal auch „implizite“ Speicher-VMs genannt) werden auf der Cluster-Übersichtsseite mit einem Bindestrich (-) anstelle eines Benutzernamens angezeigt. Benutzernamen werden nur für explizite Speichereinheiten angezeigt.


