---
sidebar: sidebar 
permalink: scpivs44_detach_a_virtual_disk.html 
keywords:  
summary: Nachdem Sie ein virtuelles Laufwerk zur Wiederherstellung einzelner Dateien angeschlossen haben, können Sie das virtuelle Laufwerk von der übergeordneten VM trennen. 
---
= Trennen Sie eine virtuelle Festplatte
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Nachdem Sie ein virtuelles Laufwerk zur Wiederherstellung einzelner Dateien angeschlossen haben, können Sie das virtuelle Laufwerk von der übergeordneten VM trennen.

.Schritte
. Wählen Sie in der VMware vSphere-Client-GUI *Menü* in der Symbolleiste aus, und wählen Sie dann *VMs und Vorlagen* aus der Dropdown-Liste aus.
. Wählen Sie im linken Navigationsbereich eine VM aus.
. Klicken Sie im linken Navigationsbereich mit der rechten Maustaste auf die VM, wählen Sie dann *SnapCenter Plug-in für VMware vSphere* in der Dropdown-Liste aus, und wählen Sie dann *virtuelles Laufwerk trennen* in der sekundären Dropdown-Liste aus.
. Wählen Sie auf dem Bildschirm *Virtuelles Laufwerk trennen* eine oder mehrere Laufwerke aus, die Sie trennen möchten, und aktivieren Sie dann das Kontrollkästchen *Ausgewählte Datenträger trennen*, und wählen Sie *TRENNEN*.
+

IMPORTANT: Stellen Sie sicher, dass Sie das richtige virtuelle Laufwerk auswählen. Die Auswahl der falschen Festplatte kann die Produktionsarbeit beeinträchtigen.

. Optional: Überwachen Sie den Arbeitsfortschritt im Abschnitt * Letzte Aufgaben*.
+
Aktualisieren Sie den Bildschirm, um aktualisierte Informationen anzuzeigen.

. Stellen Sie sicher, dass das virtuelle Laufwerk getrennt ist, indem Sie Folgendes durchführen:
+
.. Wählen Sie in der Symbolleiste *Menu* aus, und wählen Sie dann *VMs und Vorlagen* aus der Dropdown-Liste aus.
.. Klicken Sie im linken Navigationsfenster mit der rechten Maustaste auf eine VM, und wählen Sie dann in der Dropdown-Liste *Einstellungen bearbeiten* aus.
.. Erweitern Sie im Fenster *Einstellungen bearbeiten* die Liste für jede Festplatte, um die Liste der Festplattendateien anzuzeigen.
+
Auf der Seite *Edit Settings* werden die Festplatten auf der VM aufgelistet. Sie können die Details für jede Festplatte erweitern, um die Liste der verbundenen virtuellen Laufwerke anzuzeigen.




