---
sidebar: sidebar 
permalink: scpivs44_unregister_plugin_from_vcenter.html 
keywords:  
summary: Wenn Sie den SnapCenter-Plug-in für VMware vSphere-Dienst in einem vCenter im verknüpften Modus beenden, sind Ressourcengruppen nicht in allen verknüpften vCenter verfügbar, selbst wenn der SnapCenter-Plug-in für VMware vSphere-Dienst in den anderen verknüpften vCenter ausgeführt wird. Sie müssen die Registrierung des SnapCenter-Plug-ins für VMware vSphere-Erweiterungen manuell aufheben. 
---
= Heben Sie das SnapCenter Plug-in für VMware vSphere vom vCenter ab
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie den SnapCenter-Plug-in für VMware vSphere-Dienst in einem vCenter im verknüpften Modus beenden, sind Ressourcengruppen nicht in allen verknüpften vCenter verfügbar, selbst wenn der SnapCenter-Plug-in für VMware vSphere-Dienst in den anderen verknüpften vCenter ausgeführt wird.

Sie müssen die Registrierung des SnapCenter-Plug-ins für VMware vSphere-Erweiterungen manuell aufheben.

.Schritte
. Navigieren Sie auf dem Linked vCenter, bei dem der SnapCenter-Plug-in für VMware vSphere-Dienst angehalten ist, zum Manager Managed Object Reference (MOB).
. Wählen Sie in der Option Eigenschaften in der Spalte Wert die Option *Inhalt* aus, und wählen Sie dann im nächsten Bildschirm in der Spalte Wert die Option *ExtensionManager* aus, um eine Liste der registrierten Erweiterungen anzuzeigen.
. Deaktivieren Sie die Registrierung der Erweiterungen `com.netapp.scv.client` Und `com.netapp.aegis`.

