---
sidebar: sidebar 
permalink: scpivs44_minimum_ontap_privileges_required.html 
keywords:  
summary: Die erforderlichen Mindestberechtigungen für ONTAP variieren je nach SnapCenter Plug-ins, die Sie zur Datensicherung verwenden. 
---
= ONTAP-Berechtigungen erforderlich
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die erforderlichen Mindestberechtigungen für ONTAP variieren je nach SnapCenter Plug-ins, die Sie zur Datensicherung verwenden.


NOTE: Ab dem SnapCenter Plug-in für VMware (SCV) 5.0 müssen Sie Applikationen des Typs HTTP und ONTAPI als Benutzeranmeldemethoden für alle ONTAP-Benutzer mit benutzerdefiniertem rollenbasiertem Zugriff auf das SCV hinzufügen. Ohne Zugriff auf diese Applikationen können Backups fehlschlagen. Sie müssen den SCV-Dienst neu starten, um Änderungen an den ONTAP-Benutzeranmeldemethoden zu erkennen.



== Mindestberechtigungen für ONTAP erforderlich

Für alle SnapCenter Plug-ins sind die folgenden Mindestberechtigungen erforderlich.

|===


| Alle Befehle: Minimale ONTAP Privileges. 


| Event Generate-AutoSupport-log 


| Job-Verlauf wird angezeigt
Jobanzeigen
Job beenden 


| lun lun create lun delete lun igroup hinzufügen lun igroup erstellen lun igroup löschen lun igroup umbenennen lun igroup anzeigen lun Mapping add-Reporting-Nodes lun Mapping erstellen lun Mapping delete lun Mapping remove-Reporting-Nodes lun Mapping show lun modify lun move-in-Volume lun offline lun online lun persistent-reservat clear lun resize lun serial lun anzeigen 


| snapmirror list-Ziele snapmirror Policy add-rule snapmirror Policy modify-rule snapmirror Policy remove-rule snapmirror Policy show snapmirror restore SnapMirror show SnapMirror show-history snapmirror Update-ls-set snapmirror Update-ls-set 


| Version 


| Volume-Klon erstellen Volume-Klon zeigen Volume-Klon teilen starten Volume-Klon-Split-Status Volume-Clone-Split-Volume stoppen Volume erstellen Volume löschen Volume löschen Datei-Klon erstellen Volume-Datei zeigen-Disk-Nutzung Volume offline Volume online Volume-Volume verwalten Volume-Volume ändern Volume-qtree Volume erstellen qtree Volume löschen Volume-Volume ändern Volume-Snapshot Volume erstellen Volume löschen Snapshot Volume ändern Volume-SnapLock-Ablauf-Zeit Volume-Snapshot umbenennen Volume-Snapshot wiederherstellen-Datei-Volume-Snapshot wiederherstellen-Laufwerk zeigen Delta zeigen 


| vserver cifs vServer cifs Freigabe vserver erstellen cifs Freigabe vserver löschen vserver cifs shadowcopy vServer zeigen cifs share vserver zeigen vserver Export-Policy vServer Export-Policy vServer Export-Policy erstellen vServer Export-Policy löschen vServer NVMe-Subsystem vserver NVMe-Subsystem wserver vserver nvme-Subsystem abbilden vserver Export-Policy-Regel zeigen vserver Export-Policy zeigen vserver zeigen vserver iscsi vserver iscsi-Verbindung zeigen vserver zeigen vserver 
|===
|===
| Schreibgeschützte Befehle: Minimale ONTAP Privileges 


| Cluster Identity show Network Interface show vserver vserver Peer vserver show 
|===
|===
| Alle Befehle: Minimale ONTAP Privileges 


| Zeigt die Storage-Einheit der Konsistenzgruppe an 
|===
Sie können den Befehl _Cluster Identity show_ Cluster Level ignorieren, wenn Sie eine Rolle erstellen, die dem Daten-Vserver zugeordnet werden soll.


NOTE: Sie können die Warnmeldungen zu den nicht unterstützten vServer-Befehlen ignorieren.



== Weitere ONTAP-Informationen

* Zur Verwendung der SnapMirror Active Sync Funktion benötigen Sie ONTAP 9.12.1 oder höher.
* So verwenden Sie die tamperproof Snapshot (TPS)-Funktion:
+
** Für SAN benötigen Sie ONTAP 9.13.1 und höher
** Für NFS benötigen Sie ONTAP 9.12.1 und höher


* Für das NVMe over TCP- und NVMe over FC-Protokoll benötigen Sie ONTAP 9.10.1 und höher.



NOTE: Ab ONTAP Version 9.11.1 erfolgt die Kommunikation mit dem ONTAP Cluster über REST-APIs.  Der ONTAP -Benutzer sollte die HTTP-Anwendung aktiviert haben.  Wenn jedoch Probleme mit ONTAP REST-APIs auftreten, hilft der Konfigurationsschlüssel „FORCE_ZAPI“ bei der Umstellung auf den herkömmlichen ZAPI-Workflow.  Möglicherweise müssen Sie diesen Schlüssel mithilfe der Konfigurations-APIs hinzufügen oder aktualisieren und auf „true“ setzen.  Siehe KB-Artikel, https://kb.netapp.com/mgmt/SnapCenter/How_to_use_RestAPI_to_edit_configuration_parameters_in_SCV["So bearbeiten Sie Konfigurationsparameter in SCV mithilfe der RestAPI"] für weitere Informationen.
