---
sidebar: sidebar 
permalink: scpivs44_manage_storage_systems.html 
keywords:  
summary: Bevor Sie VMs oder Datastores mithilfe des VMware vSphere Clients sichern oder wiederherstellen können, müssen Sie den Storage hinzufügen. 
---
= Management von Storage-Systemen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Bevor Sie VMs oder Datastores mithilfe des VMware vSphere Clients sichern oder wiederherstellen können, müssen Sie den Storage hinzufügen.



== Ändern Sie Storage-VMs

Mit dem VMware vSphere Client können Sie die Konfigurationen der Cluster und Storage-VMs, die im SnapCenter Plug-in für VMware vSphere registriert und für VM-Datensicherungsvorgänge verwendet werden, ändern.

Wenn Sie eine Storage-VM ändern, die automatisch als Teil eines Clusters hinzugefügt wurde (manchmal auch als implizite Storage-VM bezeichnet), dann ändert sich diese Storage-VM in eine explizite Storage-VM und kann separat gelöscht werden, ohne die restlichen Storage-VMs in diesem Cluster zu ändern. Auf der Seite Storage Systems wird der Benutzername als N/A angezeigt, wenn die Authentifizierungsmethode über das Zertifikat erfolgt. Benutzernamen werden nur für explizite Speicher-VMs in der Cluster-Liste angezeigt und lassen das ExplicitSVM-Flag auf true gesetzt. Alle Storage-VMs werden immer unter dem zugehörigen Cluster aufgeführt.


IMPORTANT: Wenn Sie Storage-VMs für applikationsbasierte Datensicherungsvorgänge über die SnapCenter GUI hinzugefügt haben, müssen Sie diese Storage-VMs über dieselbe GUI ändern.

.Schritte
. Wählen Sie im linken Navigationsbereich des SCV-Plug-ins *Storage Systems* aus.
. Wählen Sie auf der Seite *Speichersysteme* die zu ändernde Speicher-VM aus und wählen Sie dann *Bearbeiten*.
. Geben Sie im Fenster *Speichersystem bearbeiten* die neuen Werte ein, und wählen Sie dann *Update*, um die Änderungen anzuwenden.




== Storage-VMs entfernen

Sie können den VMware vSphere-Client verwenden, um Storage-VMs aus dem Inventar in vCenter zu entfernen.


NOTE: Wenn Sie Storage-VMs für applikationsbasierte Datensicherungsvorgänge über die SnapCenter GUI hinzugefügt haben, müssen Sie diese Storage-VMs über dieselbe GUI ändern.

.Bevor Sie beginnen
Sie müssen alle Datenspeicher in der Storage-VM unmounten, bevor Sie die Storage-VM entfernen können.

.Über diese Aufgabe
Wenn eine Ressourcengruppe Backups enthält, die sich auf einer Speicher-VM befinden, die Sie entfernen, dann schlagen nachfolgende Backups für diese Ressourcengruppe fehl.

.Schritte
. Wählen Sie im linken Navigationsbereich des SCV-Plug-ins *Storage Systems* aus.
. Wählen Sie auf der Seite *Storage Systems* die zu entfernende Speicher-VM aus und wählen Sie dann *Delete* aus.
. Aktivieren Sie im Bestätigungsfeld *Speichersystem entfernen* das Kontrollkästchen *Speichersystem(e) löschen* und wählen Sie dann *Ja* zur Bestätigung aus. *Hinweis:* nur ESXi-Host 7.0U1 und neuere Versionen werden unterstützt.
+
link:scpivs44_restart_the_vmware_vsphere_web_client_service.html["Starten Sie den VMware vSphere-Client-Service neu"].


