---
sidebar: sidebar 
permalink: scpivs44_add_a_single_vm_or_datastore_to_a_resource_group.html 
keywords:  
summary: Sie können schnell eine einzelne VM oder einen Datastore zu einer beliebigen vorhandenen Ressourcengruppe hinzufügen, die über das SnapCenter Plug-in für VMware vSphere gemanagt wird. 
---
= Fügen Sie eine einzelne VM oder einen Datenspeicher zu einer Ressourcengruppe hinzu
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können schnell eine einzelne VM oder einen Datastore zu einer beliebigen vorhandenen Ressourcengruppe hinzufügen, die über das SnapCenter Plug-in für VMware vSphere gemanagt wird.

.Über diese Aufgabe
Fügen Sie SAN- und NAS-Datastores hinzu, aber nicht VSAN oder VVOL Datastores.

.Schritte
. Wählen Sie in der vSphere-Client-GUI in der Symbolleiste *Menü* aus, und navigieren Sie zu der VM oder dem Datastore, die Sie hinzufügen möchten.
. Klicken Sie im linken Navigationsbereich mit der rechten Maustaste auf die VM oder den Datastore, und wählen Sie in der sekundären Dropdown-Liste *SnapCenter-Plug-in für VMware vSphere* > *zu Ressourcengruppe hinzufügen* aus.
+
Das System überprüft zunächst, ob SnapCenter verwaltet und mit dem Speichersystem kompatibel ist, auf dem sich die ausgewählte VM befindet, und zeigt dann die Seite *zur Ressourcengruppe hinzufügen* an. Wenn die Meldung angezeigt wird `SnapCenter Compatibility Error` Wird angezeigt, dann ist die ausgewählte VM nicht mit SnapCenter kompatibel und Sie müssen zuerst die entsprechende Storage-VM zu SnapCenter hinzufügen.

. Wählen Sie auf der Seite *zu Ressourcengruppe hinzufügen* eine Ressourcengruppe aus, und wählen Sie dann *OK* aus.
+
Wenn Sie *OK* auswählen, prüft das System zunächst, ob SnapCenter den Speicher verwaltet und kompatibel ist, auf dem sich die ausgewählten VMs oder Datastores befinden.

+
Wenn die Meldung `Selected <resource-name> is not SnapCenter compatible` angezeigt wird, ist eine ausgewählte VM oder ein ausgewählter Datastore nicht mit SnapCenter kompatibel. Weitere Informationen finden Sie unter link:scpivs44_create_resource_groups_for_vms_and_datastores.html#manage-compatibility-check-failures["Managen Sie Fehler bei der Kompatibilitätsprüfung"] .


