---
sidebar: sidebar 
permalink: scv48_add_certificates_to_certificate_store.html 
keywords:  
summary: Fügen Sie die Root- und Intermediate-Zertifikate der Zertifizierungsstelle zum VMware vCenter hinzu, um dem Zertifikat und den Artefakten zu vertrauen, die damit signiert sind. 
---
= Fügen Sie Zertifikate zum VMware Certificate Store hinzu
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Fügen Sie vor der Installation der Open Virtual Appliance (OVA) das Zertifikat in vCenter hinzu. Die .tar-Datei enthält die OVA und die Root- und Intermediate-Zertifikate. Die Zertifikate finden Sie im Ordner Zertifikate. Die OVA-Implementierung wird in VMware vCenter 7u1 und höher unterstützt.

In VMware vCenter 7.0.3 Versionen und höher ist die OVA, die vom Vertrauenzertifikat unterzeichnet wurde, nicht mehr vertrauenswürdig. Zur Behebung des Problems müssen Sie das folgende Verfahren durchführen.

.Schritte
. Melden Sie sich mit dem vSphere Client am vCenter Server an.
. Navigieren Sie zu *Administration > Zertifikate > Zertifikatverwaltung*.
. Klicken Sie neben *Trusted Root Store* auf *Add*
. Suchen Sie nach dem Speicherort der Stammzertifikate und der Zwischenzertifikate. Das Zertifikat wird in einem Panel unter *Trusted Root Certificates* hinzugefügt. Sobald die Zertifikate installiert sind, kann OVA überprüft und bereitgestellt werden.



NOTE: Wenn das heruntergeladene OVA nicht manipuliert wird, wird in der Spalte *Publisher* *Trusted Certificate* *angezeigt.
