---
permalink: scv60_releasenotes_60_whats_new.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, scv, 6.0, 6.0.1' 
summary: Erfahren Sie mehr über die neuen Funktionen des SnapCenter Plug-in für VMware vSphere 6.0. 
---
= Neuerungen im SnapCenter Plug-in für VMware vSphere 6.0
:allow-uri-read: 


[cols="30%,70%"]
|===
| Aktualisieren | Beschreibung 


 a| 
https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_concepts_overview.html["Unterstützung für das NVMe- over TCP-Protokoll"]
 a| 
Das SnapCenter Plug-in für VMware vSphere 6.0 unterstützt jetzt das NVMe-over-TCP-Protokoll für VMFS-Datastores.

Sie benötigen keine zusätzliche Hardware, um das NVMe-over-TCP-Protokoll zu implementieren. Das vereinfacht und senkt für Sie die Kosten.

Wie bei iSCSI können VMFS-Datastores mit NVMe-over-TCP-Protokoll beliebige ethernet-NICs und -Switches verwenden und alle Standardvorgänge wie Backup, Wiederherstellung, Mounten, Verbinden und Trennen unterstützen.



 a| 
https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_create_backup_policies_for_vms_and_datastores.html["Unterstützung für SnapMirror Active Sync"]
 a| 
Jetzt können Sie das SnapCenter Plug-in für VMware vSphere verwenden, um Funktionen der aktiven SnapMirror Synchronisierung zu konfigurieren, z. B. ein Recovery Point Objective (RPO) von null, ein Recovery Time Objective (RTO) und ein transparentes Applikations-Failover.

SnapMirror Active Sync wird nur für VMFS Datastores unterstützt.

|===