---
permalink: scv_releasenotes_whats_new.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, scv, 6.2' 
summary: Informieren Sie sich über die neuen Funktionen des SnapCenter Plug-in for VMware vSphere 6.2. 
---
= Was ist neu im SnapCenter Plug-in for VMware vSphere 6.2
:allow-uri-read: 


[role="lead"]
Informieren Sie sich über die neuen Funktionen des SnapCenter Plug-in for VMware vSphere 6.2.

Das SnapCenter Plug-in for VMware vSphere 6.2 bietet Unterstützung für die Sicherung und Wiederherstellung virtueller Maschinen (VMs) auf VMFS-Datenspeichern für ASA r2-Systeme mit ONTAP 9.17.1 oder höher.  Mit dieser Version können Sie die folgenden Vorgänge für VMs, Datenspeicher und das Virtual Machine Disk (VMDK)-Format auf ASA r2-Systemen durchführen:

* Bereitstellen von Konsistenzgruppen für den primären Schutz
* Durchführen von Konsistenzgruppen-basierten Backups
* Verwenden Sie hierarchische Konsistenzgruppen (verfügbar mit ONTAP 9.17.1 und späteren Versionen)
* Ausführen von Klon-Workflows
* Ausführen von Wiederherstellungsworkflows
* Stellen Sie beim Erstellen oder Ändern von Ressourcengruppen einen sekundären Schutz bereit (verfügbar mit ONTAP 9.16.1 und späteren Versionen)

